# 逐次予測

前処理済みのデータを用いてモデルを構築し、評価する

- 目的変数: `price_actual`
- モデル: LightGBM, RandomForest, SVR, NeuralNetwork のいずれか
- 評価指標: RMSE
- ハイパーパラメータチューニング: ベイズ最適化

## 1. ライブラリのインポートとデータ読み込み

In [1]:
# 自動ローディング
%load_ext autoreload
%autoreload 2

In [2]:
# アクティベート
!source ../../.venv/bin/activate

In [3]:
# LightGBM特有のエラー対策
#!brew install libomp
#!pip uninstall lightgbm
#!pip install lightgbm

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

# データ読み込み用の関数をインポート
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
from src.data_loader import check_missing_values
from src.modeling import train_and_predict

# データディレクトリ
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / 'data'
SUBMISSION = DATA_DIR / 'submission'

os.makedirs(SUBMISSION, exist_ok=True)

print(DATA_DIR)
# 前処理済みデータの読み込み
train = pd.read_csv(DATA_DIR / 'train_processed.csv')
test = pd.read_csv(DATA_DIR / 'test_processed.csv')

print('train shape:', train.shape)
print('test shape:', test.shape)

/Users/m0122wt/Desktop/02.プライベート/01.ノウハウ/07.データ分析/notebook/signate_smbc_202506/data
train shape: (26280, 94)
test shape: (8760, 93)

## 2. 特徴量・目的変数の設定

In [5]:
# 目的変数
target_col = 'price_actual'

# 説明変数（目的変数とtime列以外）
drop_cols = ['time', target_col] if target_col in train.columns else ['time']
feature_cols = [col for col in train.columns if col not in drop_cols]

X = train[feature_cols]
y = train[target_col] if target_col in train.columns else train.iloc[:, -1]  # 念のため

print('Features:', feature_cols)
print('Target:', target_col)
print('X shape:', X.shape)
print('y shape:', y.shape)

Features: ['generation_biomass', 'generation_fossil_brown_coal/lignite', 'generation_fossil_gas', 'generation_fossil_hard_coal', 'generation_fossil_oil', 'generation_hydro_pumped_storage_consumption', 'generation_hydro_run_of_river_and_poundage', 'generation_hydro_water_reservoir', 'generation_nuclear', 'generation_other', 'generation_other_renewable', 'generation_solar', 'generation_waste', 'generation_wind_onshore', 'total_load_actual', 'valencia_pressure', 'valencia_humidity', 'valencia_wind_speed', 'valencia_wind_deg', 'valencia_rain_1h', 'valencia_rain_3h', 'valencia_snow_3h', 'valencia_clouds_all', 'madrid_pressure', 'madrid_humidity', 'madrid_wind_speed', 'madrid_wind_deg', 'madrid_rain_1h', 'madrid_rain_3h', 'madrid_snow_3h', 'madrid_clouds_all', 'bilbao_pressure', 'bilbao_humidity', 'bilbao_wind_speed', 'bilbao_wind_deg', 'bilbao_rain_1h', 'bilbao_rain_3h', 'bilbao_snow_3h', 'bilbao_clouds_all', 'barcelona_pressure', 'barcelona_humidity', 'barcelona_wind_speed', 'barcelona_wind_deg', 'barcelona_rain_1h', 'barcelona_rain_3h', 'barcelona_snow_3h', 'barcelona_clouds_all', 'seville_pressure', 'seville_humidity', 'seville_wind_speed', 'seville_wind_deg', 'seville_rain_1h', 'seville_rain_3h', 'seville_snow_3h', 'seville_clouds_all', 'hour', 'day_of_week', 'month', 'day', 'year', 'is_weekend', 'is_holiday', 'is_peak_hour', 'is_off_hour', 'generation_biomass_ratio', 'generation_fossil_brown_coal/lignite_ratio', 'generation_fossil_gas_ratio', 'generation_fossil_hard_coal_ratio', 'generation_fossil_oil_ratio', 'generation_hydro_pumped_storage_consumption_ratio', 'generation_hydro_run_of_river_and_poundage_ratio', 'generation_hydro_water_reservoir_ratio', 'generation_nuclear_ratio', 'generation_other_ratio', 'generation_other_renewable_ratio', 'generation_solar_ratio', 'generation_waste_ratio', 'generation_wind_onshore_ratio', 'non_fossil_generation', 'demand_non_fossil_diff', 'avg_temp', 'var_temp', 'avg_diff_temp', 'var_diff_temp', 'avg_weighted_weather_main', 'var_weighted_weather_main', 'price_actual_lag1', 'price_actual_lag24', 'is_holiday_or_weekend_flag', 'is_next_day_holiday_or_weekend_flag', 'is_previous_day_holiday_or_weekend_flag', 'consecutive_holiday_or_weekend_flag']
Target: price_actual
X shape: (26280, 92)
y shape: (26280,)

In [6]:
# 学習とテストデータでカラムの構成に違いがないか確認
diff_features = set(train.columns) - set(test.columns)
print("差分があるカラム:")
print(sorted(list(diff_features)))

# 欠損値の確認
check_missing_values(train)
check_missing_values(test)

差分があるカラム:
['price_actual']
欠損値があるカラム、欠損値の数、全レコードに対する割合:

Empty DataFrame
Columns: [missing_count, missing_ratio]
Index: []

欠損値があるカラム、欠損値の数、全レコードに対する割合:

Empty DataFrame
Columns: [missing_count, missing_ratio]
Index: []

## 3. 学習・検証

In [ ]:
%%time
filename = 'submission_nn'

# 通常の予測
model, predictions = train_and_predict(
    model_type='neural_network',
    train_df=train,
    test_df=test,
    target_col='price_actual',
    optimize=True,
    sequential=False,  # 通常予測
    output_path=SUBMISSION,
    filename=filename
)

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 19:28:31,277] Trial 0 finished with value: 4.230525019088106 and parameters: {'layer1_units': 161, 'layer2_units': 97, 'layer3_units': 43, 'dropout_rate': 0.15593898501118525, 'learning_rate': 0.0031550822395662132, 'batch_size': 16}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step

[I 2025-06-29 19:29:39,251] Trial 1 finished with value: 6.310324773774258 and parameters: {'layer1_units': 70, 'layer2_units': 116, 'layer3_units': 50, 'dropout_rate': 0.1488832508429328, 'learning_rate': 0.0004478445203864317, 'batch_size': 32}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step

[I 2025-06-29 19:30:31,748] Trial 2 finished with value: 6.049757395132216 and parameters: {'layer1_units': 214, 'layer2_units': 88, 'layer3_units': 8, 'dropout_rate': 0.3130829996262918, 'learning_rate': 0.008485738539093183, 'batch_size': 64}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step

[I 2025-06-29 19:31:02,959] Trial 3 finished with value: 8.262017497596588 and parameters: {'layer1_units': 187, 'layer2_units': 17, 'layer3_units': 37, 'dropout_rate': 0.2950108209868218, 'learning_rate': 0.0037491336692768375, 'batch_size': 64}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step

[I 2025-06-29 19:33:10,077] Trial 4 finished with value: 5.38673033763488 and parameters: {'layer1_units': 256, 'layer2_units': 79, 'layer3_units': 35, 'dropout_rate': 0.3931114621391111, 'learning_rate': 0.000682337631968599, 'batch_size': 16}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step

[I 2025-06-29 19:34:07,447] Trial 5 finished with value: 4.448570642364585 and parameters: {'layer1_units': 150, 'layer2_units': 36, 'layer3_units': 36, 'dropout_rate': 0.42720970617455145, 'learning_rate': 0.009890709570003526, 'batch_size': 64}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step

[I 2025-06-29 19:35:19,213] Trial 6 finished with value: 9.369788540087402 and parameters: {'layer1_units': 85, 'layer2_units': 31, 'layer3_units': 28, 'dropout_rate': 0.4997735435093569, 'learning_rate': 0.0001830679947368454, 'batch_size': 64}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step

[I 2025-06-29 19:36:44,906] Trial 7 finished with value: 5.147494982523935 and parameters: {'layer1_units': 142, 'layer2_units': 92, 'layer3_units': 11, 'dropout_rate': 0.43000085741675587, 'learning_rate': 0.007319769788023053, 'batch_size': 32}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step

[I 2025-06-29 19:38:48,306] Trial 8 finished with value: 5.514330870590259 and parameters: {'layer1_units': 104, 'layer2_units': 62, 'layer3_units': 60, 'dropout_rate': 0.12386921014041415, 'learning_rate': 0.00016955660571969634, 'batch_size': 16}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step

[I 2025-06-29 19:39:44,176] Trial 9 finished with value: 6.323367262923014 and parameters: {'layer1_units': 226, 'layer2_units': 34, 'layer3_units': 49, 'dropout_rate': 0.2525069644827248, 'learning_rate': 0.004045696656476189, 'batch_size': 32}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step

[I 2025-06-29 19:41:01,049] Trial 10 finished with value: 5.3661303550420545 and parameters: {'layer1_units': 43, 'layer2_units': 126, 'layer3_units': 22, 'dropout_rate': 0.20571165480928738, 'learning_rate': 0.0016745155455120285, 'batch_size': 16}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step

[I 2025-06-29 19:43:10,899] Trial 11 finished with value: 5.041522155894974 and parameters: {'layer1_units': 153, 'layer2_units': 56, 'layer3_units': 44, 'dropout_rate': 0.37276681927649835, 'learning_rate': 0.0018468491570539942, 'batch_size': 16}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step

[I 2025-06-29 19:43:51,530] Trial 12 finished with value: 5.468241988379333 and parameters: {'layer1_units': 142, 'layer2_units': 104, 'layer3_units': 39, 'dropout_rate': 0.4961299184087005, 'learning_rate': 0.0036602586955848245, 'batch_size': 64}. Best is trial 0 with value: 4.230525019088106.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step

[I 2025-06-29 19:47:31,645] Trial 13 finished with value: 4.136510684547099 and parameters: {'layer1_units': 165, 'layer2_units': 55, 'layer3_units': 59, 'dropout_rate': 0.20833311349819833, 'learning_rate': 0.009339140656643803, 'batch_size': 16}. Best is trial 13 with value: 4.136510684547099.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step

[I 2025-06-29 19:49:54,191] Trial 14 finished with value: 4.492383456220145 and parameters: {'layer1_units': 185, 'layer2_units': 60, 'layer3_units': 64, 'dropout_rate': 0.18934468215432407, 'learning_rate': 0.0017506324198699728, 'batch_size': 16}. Best is trial 13 with value: 4.136510684547099.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step

[I 2025-06-29 19:52:10,612] Trial 15 finished with value: 3.9443300126446155 and parameters: {'layer1_units': 115, 'layer2_units': 76, 'layer3_units': 56, 'dropout_rate': 0.10661187021250612, 'learning_rate': 0.004906027149645123, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step

[I 2025-06-29 19:53:53,095] Trial 16 finished with value: 3.951383534976941 and parameters: {'layer1_units': 114, 'layer2_units': 70, 'layer3_units': 55, 'dropout_rate': 0.10972589006170565, 'learning_rate': 0.006013095896438398, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 774us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step

[I 2025-06-29 19:56:12,843] Trial 17 finished with value: 5.354657253563724 and parameters: {'layer1_units': 110, 'layer2_units': 74, 'layer3_units': 53, 'dropout_rate': 0.1028332840666291, 'learning_rate': 0.0007638487631149338, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step

[I 2025-06-29 19:58:10,003] Trial 18 finished with value: 4.128867676312059 and parameters: {'layer1_units': 117, 'layer2_units': 80, 'layer3_units': 55, 'dropout_rate': 0.16640101540712066, 'learning_rate': 0.005157770744887759, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 786us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 19:59:46,175] Trial 19 finished with value: 5.616986564047162 and parameters: {'layer1_units': 39, 'layer2_units': 46, 'layer3_units': 64, 'dropout_rate': 0.24890870407174048, 'learning_rate': 0.002355922050822228, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step

[I 2025-06-29 20:01:08,645] Trial 20 finished with value: 4.609365826030116 and parameters: {'layer1_units': 69, 'layer2_units': 69, 'layer3_units': 47, 'dropout_rate': 0.10023527209007564, 'learning_rate': 0.005696629622116645, 'batch_size': 32}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step

[I 2025-06-29 20:03:32,896] Trial 21 finished with value: 4.4863943845258785 and parameters: {'layer1_units': 117, 'layer2_units': 81, 'layer3_units': 55, 'dropout_rate': 0.1587418961858456, 'learning_rate': 0.005556126546286104, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 20:06:01,753] Trial 22 finished with value: 4.49987521871342 and parameters: {'layer1_units': 123, 'layer2_units': 103, 'layer3_units': 55, 'dropout_rate': 0.14255864293303644, 'learning_rate': 0.005423964867105583, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 639us/step

[I 2025-06-29 20:07:57,199] Trial 23 finished with value: 4.990025508646404 and parameters: {'layer1_units': 87, 'layer2_units': 70, 'layer3_units': 59, 'dropout_rate': 0.1718612363547, 'learning_rate': 0.0011694154839981727, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step

[I 2025-06-29 20:10:11,111] Trial 24 finished with value: 4.596736133950335 and parameters: {'layer1_units': 127, 'layer2_units': 86, 'layer3_units': 52, 'dropout_rate': 0.23144869815702737, 'learning_rate': 0.0024780338724263665, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step

[I 2025-06-29 20:12:16,131] Trial 25 finished with value: 4.322334161422132 and parameters: {'layer1_units': 95, 'layer2_units': 45, 'layer3_units': 45, 'dropout_rate': 0.12299991719361858, 'learning_rate': 0.0050002855143260454, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step

[I 2025-06-29 20:13:47,164] Trial 26 finished with value: 5.299486958600963 and parameters: {'layer1_units': 60, 'layer2_units': 65, 'layer3_units': 56, 'dropout_rate': 0.2937948918000608, 'learning_rate': 0.002887278117628883, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step

[I 2025-06-29 20:15:46,218] Trial 27 finished with value: 4.382780773781843 and parameters: {'layer1_units': 128, 'layer2_units': 73, 'layer3_units': 60, 'dropout_rate': 0.12892811404905713, 'learning_rate': 0.001147146918429864, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 761us/step

[I 2025-06-29 20:16:52,167] Trial 28 finished with value: 5.125859910405043 and parameters: {'layer1_units': 103, 'layer2_units': 83, 'layer3_units': 30, 'dropout_rate': 0.17931036888958896, 'learning_rate': 0.006672987049025507, 'batch_size': 32}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step

[I 2025-06-29 20:19:41,098] Trial 29 finished with value: 6.944626169214894 and parameters: {'layer1_units': 83, 'layer2_units': 98, 'layer3_units': 41, 'dropout_rate': 0.10076390987221545, 'learning_rate': 0.00011904892458318019, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step

[I 2025-06-29 20:22:13,644] Trial 30 finished with value: 4.0222632581817335 and parameters: {'layer1_units': 163, 'layer2_units': 94, 'layer3_units': 48, 'dropout_rate': 0.15918722211862818, 'learning_rate': 0.004173985181009339, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step

[I 2025-06-29 20:24:58,648] Trial 31 finished with value: 4.287892846735699 and parameters: {'layer1_units': 173, 'layer2_units': 95, 'layer3_units': 49, 'dropout_rate': 0.15413871749240843, 'learning_rate': 0.004180721645679742, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step

[I 2025-06-29 20:28:05,538] Trial 32 finished with value: 4.04673228332401 and parameters: {'layer1_units': 137, 'layer2_units': 110, 'layer3_units': 53, 'dropout_rate': 0.13273161114858606, 'learning_rate': 0.0028371506109063967, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step

[I 2025-06-29 20:30:16,615] Trial 33 finished with value: 4.84163453213972 and parameters: {'layer1_units': 136, 'layer2_units': 115, 'layer3_units': 51, 'dropout_rate': 0.13763749610322454, 'learning_rate': 0.002430750337995981, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step

[I 2025-06-29 20:32:41,729] Trial 34 finished with value: 4.83877037838934 and parameters: {'layer1_units': 201, 'layer2_units': 113, 'layer3_units': 46, 'dropout_rate': 0.2065190533814057, 'learning_rate': 0.0029993398538494327, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 788us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step

[I 2025-06-29 20:34:39,646] Trial 35 finished with value: 5.1764314837591465 and parameters: {'layer1_units': 163, 'layer2_units': 127, 'layer3_units': 49, 'dropout_rate': 0.12167081642458938, 'learning_rate': 0.0003602225945947477, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step

[I 2025-06-29 20:35:36,992] Trial 36 finished with value: 4.797368840475984 and parameters: {'layer1_units': 175, 'layer2_units': 107, 'layer3_units': 41, 'dropout_rate': 0.151412431437486, 'learning_rate': 0.0074337301938393755, 'batch_size': 64}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step

[I 2025-06-29 20:36:39,191] Trial 37 finished with value: 4.699796932750745 and parameters: {'layer1_units': 154, 'layer2_units': 88, 'layer3_units': 58, 'dropout_rate': 0.1913194131129678, 'learning_rate': 0.0038905658547462307, 'batch_size': 32}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step

[I 2025-06-29 20:37:32,830] Trial 38 finished with value: 5.208545659943651 and parameters: {'layer1_units': 201, 'layer2_units': 110, 'layer3_units': 63, 'dropout_rate': 0.27280094599044485, 'learning_rate': 0.0015208399627330434, 'batch_size': 64}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step

[I 2025-06-29 20:39:22,443] Trial 39 finished with value: 4.200477276633727 and parameters: {'layer1_units': 133, 'layer2_units': 99, 'layer3_units': 33, 'dropout_rate': 0.22664856544359904, 'learning_rate': 0.007670242385167869, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 718us/step

[I 2025-06-29 20:41:06,473] Trial 40 finished with value: 4.7622751974145086 and parameters: {'layer1_units': 147, 'layer2_units': 90, 'layer3_units': 18, 'dropout_rate': 0.3310791774859331, 'learning_rate': 0.003328388129226594, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step

[I 2025-06-29 20:42:36,418] Trial 41 finished with value: 4.393595394811578 and parameters: {'layer1_units': 114, 'layer2_units': 77, 'layer3_units': 53, 'dropout_rate': 0.16915287089843636, 'learning_rate': 0.004659582119130583, 'batch_size': 16}. Best is trial 15 with value: 3.9443300126446155.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step

[I 2025-06-29 20:44:23,651] Trial 42 finished with value: 3.8384182347548994 and parameters: {'layer1_units': 99, 'layer2_units': 79, 'layer3_units': 56, 'dropout_rate': 0.11254910827768753, 'learning_rate': 0.0067228296410061375, 'batch_size': 16}. Best is trial 42 with value: 3.8384182347548994.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step

[I 2025-06-29 20:46:21,797] Trial 43 finished with value: 3.882841128179608 and parameters: {'layer1_units': 99, 'layer2_units': 122, 'layer3_units': 57, 'dropout_rate': 0.11716239568717893, 'learning_rate': 0.009151099036373154, 'batch_size': 16}. Best is trial 42 with value: 3.8384182347548994.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step

[I 2025-06-29 20:48:04,178] Trial 44 finished with value: 3.7834964789155463 and parameters: {'layer1_units': 97, 'layer2_units': 121, 'layer3_units': 61, 'dropout_rate': 0.11902223485177482, 'learning_rate': 0.009908995663016463, 'batch_size': 16}. Best is trial 44 with value: 3.7834964789155463.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step

[I 2025-06-29 20:48:42,241] Trial 45 finished with value: 4.68123086883339 and parameters: {'layer1_units': 96, 'layer2_units': 120, 'layer3_units': 62, 'dropout_rate': 0.11541012280195617, 'learning_rate': 0.009589826155426107, 'batch_size': 64}. Best is trial 44 with value: 3.7834964789155463.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step

[I 2025-06-29 20:50:03,731] Trial 46 finished with value: 3.9673402782922436 and parameters: {'layer1_units': 73, 'layer2_units': 120, 'layer3_units': 57, 'dropout_rate': 0.11858803142237605, 'learning_rate': 0.0074187674088621106, 'batch_size': 16}. Best is trial 44 with value: 3.7834964789155463.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step

[I 2025-06-29 20:52:48,664] Trial 47 finished with value: 4.819992034502951 and parameters: {'layer1_units': 60, 'layer2_units': 23, 'layer3_units': 62, 'dropout_rate': 0.1430642101363748, 'learning_rate': 0.006019536648907727, 'batch_size': 32}. Best is trial 44 with value: 3.7834964789155463.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step

[I 2025-06-29 20:54:32,329] Trial 48 finished with value: 3.689259275388217 and parameters: {'layer1_units': 102, 'layer2_units': 55, 'layer3_units': 61, 'dropout_rate': 0.10640580695705512, 'learning_rate': 0.007598245111982641, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step

[I 2025-06-29 20:56:01,412] Trial 49 finished with value: 4.52014774213792 and parameters: {'layer1_units': 98, 'layer2_units': 50, 'layer3_units': 60, 'dropout_rate': 0.44666978625308146, 'learning_rate': 0.008220426224609723, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step

[I 2025-06-29 20:57:33,893] Trial 50 finished with value: 4.01231158357096 and parameters: {'layer1_units': 80, 'layer2_units': 40, 'layer3_units': 61, 'dropout_rate': 0.18790509475463935, 'learning_rate': 0.00965220760807586, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step

[I 2025-06-29 20:59:20,840] Trial 51 finished with value: 3.7692249086859007 and parameters: {'layer1_units': 109, 'layer2_units': 62, 'layer3_units': 57, 'dropout_rate': 0.11079659532513528, 'learning_rate': 0.0065189316031648206, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step

[I 2025-06-29 21:00:45,790] Trial 52 finished with value: 3.945805826007388 and parameters: {'layer1_units': 106, 'layer2_units': 57, 'layer3_units': 58, 'dropout_rate': 0.13383776865318175, 'learning_rate': 0.009831817581938898, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step

[I 2025-06-29 21:02:22,661] Trial 53 finished with value: 4.031678987856963 and parameters: {'layer1_units': 89, 'layer2_units': 66, 'layer3_units': 57, 'dropout_rate': 0.1115585680354988, 'learning_rate': 0.006761750996863064, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step

[I 2025-06-29 21:04:02,138] Trial 54 finished with value: 3.8726206479754355 and parameters: {'layer1_units': 76, 'layer2_units': 61, 'layer3_units': 64, 'dropout_rate': 0.10157584618920126, 'learning_rate': 0.00827746489442154, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step

[I 2025-06-29 21:05:23,280] Trial 55 finished with value: 5.6488176799948695 and parameters: {'layer1_units': 55, 'layer2_units': 53, 'layer3_units': 63, 'dropout_rate': 0.14491432869660928, 'learning_rate': 0.00044501531462366484, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step

[I 2025-06-29 21:06:02,555] Trial 56 finished with value: 4.5102000937372315 and parameters: {'layer1_units': 74, 'layer2_units': 61, 'layer3_units': 61, 'dropout_rate': 0.12691137908766034, 'learning_rate': 0.008530038063078648, 'batch_size': 64}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step

[I 2025-06-29 21:08:10,301] Trial 57 finished with value: 4.3202997080205074 and parameters: {'layer1_units': 46, 'layer2_units': 122, 'layer3_units': 59, 'dropout_rate': 0.10318132012838553, 'learning_rate': 0.006376789739689719, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step

[I 2025-06-29 21:09:24,321] Trial 58 finished with value: 4.391925718790693 and parameters: {'layer1_units': 32, 'layer2_units': 47, 'layer3_units': 24, 'dropout_rate': 0.3430519560421588, 'learning_rate': 0.008004824900553813, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step

[I 2025-06-29 21:10:14,657] Trial 59 finished with value: 4.956765379842755 and parameters: {'layer1_units': 91, 'layer2_units': 38, 'layer3_units': 64, 'dropout_rate': 0.11740777753496544, 'learning_rate': 0.004654296874354554, 'batch_size': 32}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step

[I 2025-06-29 21:11:54,522] Trial 60 finished with value: 4.627672251416117 and parameters: {'layer1_units': 104, 'layer2_units': 65, 'layer3_units': 51, 'dropout_rate': 0.15189502050850573, 'learning_rate': 0.006276138428707341, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step

[I 2025-06-29 21:13:42,950] Trial 61 finished with value: 3.9174816011542637 and parameters: {'layer1_units': 122, 'layer2_units': 57, 'layer3_units': 55, 'dropout_rate': 0.10272747722742412, 'learning_rate': 0.008551545792063929, 'batch_size': 16}. Best is trial 48 with value: 3.689259275388217.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step

[I 2025-06-29 21:15:40,551] Trial 62 finished with value: 3.5697693374659956 and parameters: {'layer1_units': 121, 'layer2_units': 59, 'layer3_units': 54, 'dropout_rate': 0.13383472933292856, 'learning_rate': 0.00830555831035743, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 705us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step

[I 2025-06-29 21:17:40,360] Trial 63 finished with value: 3.7129240403356563 and parameters: {'layer1_units': 108, 'layer2_units': 52, 'layer3_units': 61, 'dropout_rate': 0.1344489347113747, 'learning_rate': 0.006995386388321294, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 714us/step

[I 2025-06-29 21:19:11,713] Trial 64 finished with value: 3.8019617273653226 and parameters: {'layer1_units': 109, 'layer2_units': 52, 'layer3_units': 64, 'dropout_rate': 0.1347390484486642, 'learning_rate': 0.007043600156777256, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step

[I 2025-06-29 21:21:04,643] Trial 65 finished with value: 4.2627932689435895 and parameters: {'layer1_units': 246, 'layer2_units': 42, 'layer3_units': 61, 'dropout_rate': 0.17246200165973685, 'learning_rate': 0.005396174001820409, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 625us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step

[I 2025-06-29 21:23:02,412] Trial 66 finished with value: 3.9002405740997332 and parameters: {'layer1_units': 111, 'layer2_units': 32, 'layer3_units': 53, 'dropout_rate': 0.13602137493226318, 'learning_rate': 0.006580964969281499, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step

[I 2025-06-29 21:24:41,825] Trial 67 finished with value: 3.810854622866246 and parameters: {'layer1_units': 123, 'layer2_units': 52, 'layer3_units': 60, 'dropout_rate': 0.1596302041576192, 'learning_rate': 0.004772013666988672, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step

[I 2025-06-29 21:26:31,500] Trial 68 finished with value: 3.969088943528046 and parameters: {'layer1_units': 123, 'layer2_units': 54, 'layer3_units': 62, 'dropout_rate': 0.189549031800955, 'learning_rate': 0.004510284912450639, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step

[I 2025-06-29 21:27:52,963] Trial 69 finished with value: 4.135499665174455 and parameters: {'layer1_units': 131, 'layer2_units': 51, 'layer3_units': 59, 'dropout_rate': 0.15889580401379705, 'learning_rate': 0.0057516007447616195, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step

[I 2025-06-29 21:29:25,147] Trial 70 finished with value: 4.549910844821108 and parameters: {'layer1_units': 140, 'layer2_units': 48, 'layer3_units': 60, 'dropout_rate': 0.14260632020901975, 'learning_rate': 0.003676089040082214, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step

[I 2025-06-29 21:33:00,659] Trial 71 finished with value: 3.768693814897992 and parameters: {'layer1_units': 108, 'layer2_units': 57, 'layer3_units': 56, 'dropout_rate': 0.12882241024500968, 'learning_rate': 0.006984043824468088, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2025-06-29 21:48:02,454] Trial 72 finished with value: 3.987551377950272 and parameters: {'layer1_units': 119, 'layer2_units': 43, 'layer3_units': 9, 'dropout_rate': 0.12920004088693543, 'learning_rate': 0.007251961054194633, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step

[I 2025-06-29 22:00:19,096] Trial 73 finished with value: 4.046213081545791 and parameters: {'layer1_units': 108, 'layer2_units': 58, 'layer3_units': 64, 'dropout_rate': 0.18020723236969394, 'learning_rate': 0.005036363695259283, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step

[I 2025-06-29 22:04:20,155] Trial 74 finished with value: 3.966821796312336 and parameters: {'layer1_units': 126, 'layer2_units': 68, 'layer3_units': 54, 'dropout_rate': 0.163562650862943, 'learning_rate': 0.007393138725391173, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 718us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step

[I 2025-06-29 22:21:45,097] Trial 75 finished with value: 4.104250699838352 and parameters: {'layer1_units': 92, 'layer2_units': 51, 'layer3_units': 58, 'dropout_rate': 0.12751848599847762, 'learning_rate': 0.005684162307937166, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step

[I 2025-06-29 22:23:05,612] Trial 76 finished with value: 4.546189841516191 and parameters: {'layer1_units': 112, 'layer2_units': 63, 'layer3_units': 51, 'dropout_rate': 0.1422986413546625, 'learning_rate': 0.009903445587109845, 'batch_size': 32}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step

[I 2025-06-29 22:37:13,083] Trial 77 finished with value: 4.921109715510423 and parameters: {'layer1_units': 84, 'layer2_units': 59, 'layer3_units': 62, 'dropout_rate': 0.21586184011649984, 'learning_rate': 0.0033172073923131294, 'batch_size': 64}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 22:38:43,896] Trial 78 finished with value: 3.9275631472904124 and parameters: {'layer1_units': 118, 'layer2_units': 55, 'layer3_units': 60, 'dropout_rate': 0.15044632338978314, 'learning_rate': 0.008629741621669908, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step

[I 2025-06-29 22:56:23,341] Trial 79 finished with value: 3.751877371547234 and parameters: {'layer1_units': 103, 'layer2_units': 71, 'layer3_units': 56, 'dropout_rate': 0.3937361971281578, 'learning_rate': 0.005093208676395223, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 764us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step

[I 2025-06-29 22:57:59,462] Trial 80 finished with value: 5.54352227579853 and parameters: {'layer1_units': 103, 'layer2_units': 70, 'layer3_units': 54, 'dropout_rate': 0.4796321869827313, 'learning_rate': 0.0008168302078829061, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step

[I 2025-06-29 23:00:04,175] Trial 81 finished with value: 3.829462314243395 and parameters: {'layer1_units': 110, 'layer2_units': 62, 'layer3_units': 58, 'dropout_rate': 0.3942738538358721, 'learning_rate': 0.004381599489227125, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step

[I 2025-06-29 23:18:03,036] Trial 82 finished with value: 5.674091299210121 and parameters: {'layer1_units': 128, 'layer2_units': 72, 'layer3_units': 55, 'dropout_rate': 0.30336279663375926, 'learning_rate': 0.0002570397156951883, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step

[I 2025-06-29 23:19:33,788] Trial 83 finished with value: 4.128094516229803 and parameters: {'layer1_units': 102, 'layer2_units': 53, 'layer3_units': 57, 'dropout_rate': 0.3749016401743343, 'learning_rate': 0.005084461603627918, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step

[I 2025-06-29 23:37:45,654] Trial 84 finished with value: 4.207672627735285 and parameters: {'layer1_units': 93, 'layer2_units': 49, 'layer3_units': 60, 'dropout_rate': 0.4195734920399692, 'learning_rate': 0.007089647333177422, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 725us/step

[I 2025-06-29 23:54:50,732] Trial 85 finished with value: 4.043870073884838 and parameters: {'layer1_units': 119, 'layer2_units': 46, 'layer3_units': 63, 'dropout_rate': 0.27403125782368454, 'learning_rate': 0.006092316088430371, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 694us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step

[I 2025-06-30 00:12:24,030] Trial 86 finished with value: 3.8640160880122516 and parameters: {'layer1_units': 108, 'layer2_units': 76, 'layer3_units': 56, 'dropout_rate': 0.1211518487483923, 'learning_rate': 0.007694044157433784, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step

[I 2025-06-30 00:18:37,033] Trial 87 finished with value: 4.121792196646117 and parameters: {'layer1_units': 144, 'layer2_units': 67, 'layer3_units': 59, 'dropout_rate': 0.13127793234037477, 'learning_rate': 0.008741759569932171, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step

[I 2025-06-30 00:20:25,651] Trial 88 finished with value: 3.7240252163131884 and parameters: {'layer1_units': 114, 'layer2_units': 44, 'layer3_units': 52, 'dropout_rate': 0.11289816644578017, 'learning_rate': 0.005300174659074469, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step

[I 2025-06-30 00:22:23,432] Trial 89 finished with value: 3.7388130058850018 and parameters: {'layer1_units': 81, 'layer2_units': 44, 'layer3_units': 50, 'dropout_rate': 0.11202842508476553, 'learning_rate': 0.005775720492201894, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step

[I 2025-06-30 00:22:54,649] Trial 90 finished with value: 5.753671998709449 and parameters: {'layer1_units': 87, 'layer2_units': 25, 'layer3_units': 50, 'dropout_rate': 0.112144532499326, 'learning_rate': 0.0040988396537868345, 'batch_size': 64}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 647us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step

[I 2025-06-30 00:24:45,672] Trial 91 finished with value: 3.7334135442901735 and parameters: {'layer1_units': 98, 'layer2_units': 42, 'layer3_units': 47, 'dropout_rate': 0.10976256511888169, 'learning_rate': 0.005498787431468812, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 761us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 718us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step

[I 2025-06-30 00:26:19,646] Trial 92 finished with value: 4.46980084487601 and parameters: {'layer1_units': 80, 'layer2_units': 34, 'layer3_units': 43, 'dropout_rate': 0.11011606112161244, 'learning_rate': 0.0020777663969868045, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-30 00:27:36,650] Trial 93 finished with value: 4.5120315898251455 and parameters: {'layer1_units': 69, 'layer2_units': 37, 'layer3_units': 48, 'dropout_rate': 0.12047363124657068, 'learning_rate': 0.005834360289550642, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step

[I 2025-06-30 00:29:23,094] Trial 94 finished with value: 3.9210304677712466 and parameters: {'layer1_units': 97, 'layer2_units': 40, 'layer3_units': 52, 'dropout_rate': 0.10025964184987635, 'learning_rate': 0.005363028426296034, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step

[I 2025-06-30 00:30:51,483] Trial 95 finished with value: 4.890687263993099 and parameters: {'layer1_units': 68, 'layer2_units': 44, 'layer3_units': 47, 'dropout_rate': 0.1098698924188863, 'learning_rate': 0.003654744123213264, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step

[I 2025-06-30 00:32:07,785] Trial 96 finished with value: 4.539646216310026 and parameters: {'layer1_units': 115, 'layer2_units': 41, 'layer3_units': 37, 'dropout_rate': 0.12251815422397921, 'learning_rate': 0.006293349556017581, 'batch_size': 32}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step

[I 2025-06-30 00:33:51,788] Trial 97 finished with value: 4.1436695499354315 and parameters: {'layer1_units': 101, 'layer2_units': 63, 'layer3_units': 54, 'dropout_rate': 0.33218196452790033, 'learning_rate': 0.00791291940757715, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step

[I 2025-06-30 00:35:58,860] Trial 98 finished with value: 3.6971392596244996 and parameters: {'layer1_units': 88, 'layer2_units': 83, 'layer3_units': 51, 'dropout_rate': 0.1382797753393795, 'learning_rate': 0.008878697502776495, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step

[I 2025-06-30 00:37:54,237] Trial 99 finished with value: 3.9706310968425114 and parameters: {'layer1_units': 83, 'layer2_units': 81, 'layer3_units': 45, 'dropout_rate': 0.14701880532967096, 'learning_rate': 0.006667083946223166, 'batch_size': 16}. Best is trial 62 with value: 3.5697693374659956.

NEURAL_NETWORK：ベイズ最適化の結果
Best params: {'layer1_units': 121, 'layer2_units': 59, 'layer3_units': 54, 'dropout_rate': 0.13383472933292856, 'learning_rate': 0.00830555831035743, 'batch_size': 16, 'hidden_layers': [121, 59, 54], 'epochs': 100, 'patience': 10}
Best CV RMSE: 3.5697693374659956
Epoch 1/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 5s 558us/step - loss: 187.1805 - mae: 9.7255 - learning_rate: 0.0083
Epoch 2/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 621us/step - loss: 72.2817 - mae: 6.6152 - learning_rate: 0.0083
Epoch 3/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 567us/step - loss: 47.7895 - mae: 5.3363 - learning_rate: 0.0083
Epoch 4/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - loss: 40.4110 - mae: 4.8910 - learning_rate: 0.0083
Epoch 5/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 551us/step - loss: 36.6129 - mae: 4.6500 - learning_rate: 0.0083
Epoch 6/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 543us/step - loss: 34.8053 - mae: 4.5237 - learning_rate: 0.0083
Epoch 7/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 569us/step - loss: 30.8224 - mae: 4.2850 - learning_rate: 0.0083
Epoch 8/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 563us/step - loss: 29.1840 - mae: 4.1289 - learning_rate: 0.0083
Epoch 9/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 569us/step - loss: 27.7496 - mae: 4.0047 - learning_rate: 0.0083
Epoch 10/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 549us/step - loss: 26.3729 - mae: 3.9336 - learning_rate: 0.0083
Epoch 11/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 548us/step - loss: 24.7359 - mae: 3.7984 - learning_rate: 0.0083
Epoch 12/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 613us/step - loss: 23.8643 - mae: 3.7487 - learning_rate: 0.0083
Epoch 13/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 550us/step - loss: 22.1898 - mae: 3.5870 - learning_rate: 0.0083
Epoch 14/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 550us/step - loss: 22.8548 - mae: 3.6312 - learning_rate: 0.0083
Epoch 15/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 552us/step - loss: 21.0801 - mae: 3.5100 - learning_rate: 0.0083
Epoch 16/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 554us/step - loss: 21.4186 - mae: 3.5230 - learning_rate: 0.0083
Epoch 17/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 547us/step - loss: 21.1845 - mae: 3.5097 - learning_rate: 0.0083
Epoch 18/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 553us/step - loss: 22.2231 - mae: 3.5743 - learning_rate: 0.0083
Epoch 19/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 550us/step - loss: 21.4590 - mae: 3.5220 - learning_rate: 0.0083
Epoch 20/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 554us/step - loss: 20.2914 - mae: 3.4332 - learning_rate: 0.0083
Epoch 21/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 560us/step - loss: 19.8977 - mae: 3.3645 - learning_rate: 0.0083
Epoch 22/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 607us/step - loss: 20.3933 - mae: 3.3782 - learning_rate: 0.0083
Epoch 23/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 586us/step - loss: 19.7075 - mae: 3.2987 - learning_rate: 0.0083
Epoch 24/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 572us/step - loss: 20.6259 - mae: 3.3853 - learning_rate: 0.0083
Epoch 25/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 573us/step - loss: 19.7479 - mae: 3.2796 - learning_rate: 0.0083
Epoch 26/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 550us/step - loss: 19.4309 - mae: 3.2817 - learning_rate: 0.0083
Epoch 27/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 554us/step - loss: 19.2543 - mae: 3.2338 - learning_rate: 0.0083
Epoch 28/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 552us/step - loss: 19.8526 - mae: 3.3060 - learning_rate: 0.0083
Epoch 29/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 562us/step - loss: 19.2450 - mae: 3.2277 - learning_rate: 0.0083
Epoch 30/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 555us/step - loss: 19.5855 - mae: 3.2472 - learning_rate: 0.0083
Epoch 31/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - loss: 19.1921 - mae: 3.1710 - learning_rate: 0.0083
Epoch 32/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 552us/step - loss: 17.1213 - mae: 3.0084 - learning_rate: 0.0042
Epoch 33/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 556us/step - loss: 16.7295 - mae: 2.9399 - learning_rate: 0.0042
Epoch 34/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 559us/step - loss: 16.0619 - mae: 2.8860 - learning_rate: 0.0042
Epoch 35/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 557us/step - loss: 16.1574 - mae: 2.8965 - learning_rate: 0.0042
Epoch 36/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 555us/step - loss: 15.7229 - mae: 2.8422 - learning_rate: 0.0042
Epoch 37/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 568us/step - loss: 16.1953 - mae: 2.8612 - learning_rate: 0.0042
Epoch 38/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 643us/step - loss: 15.5702 - mae: 2.8323 - learning_rate: 0.0042
Epoch 39/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 647us/step - loss: 15.3759 - mae: 2.8203 - learning_rate: 0.0042
Epoch 40/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 611us/step - loss: 14.9182 - mae: 2.7881 - learning_rate: 0.0042
Epoch 41/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 560us/step - loss: 15.7341 - mae: 2.8289 - learning_rate: 0.0042
Epoch 42/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 558us/step - loss: 15.0152 - mae: 2.7769 - learning_rate: 0.0042
Epoch 43/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 552us/step - loss: 15.7100 - mae: 2.8472 - learning_rate: 0.0042
Epoch 44/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 655us/step - loss: 15.0321 - mae: 2.8214 - learning_rate: 0.0042
Epoch 45/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 555us/step - loss: 15.3573 - mae: 2.8008 - learning_rate: 0.0042
Epoch 46/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 559us/step - loss: 14.8562 - mae: 2.7763 - learning_rate: 0.0042
Epoch 47/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 555us/step - loss: 15.4274 - mae: 2.8095 - learning_rate: 0.0042
Epoch 48/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 557us/step - loss: 14.7537 - mae: 2.7695 - learning_rate: 0.0042
Epoch 49/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 620us/step - loss: 14.9410 - mae: 2.7619 - learning_rate: 0.0042
Epoch 50/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 554us/step - loss: 14.4208 - mae: 2.7423 - learning_rate: 0.0042
Epoch 51/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 561us/step - loss: 15.2252 - mae: 2.7874 - learning_rate: 0.0042
Epoch 52/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 573us/step - loss: 14.9997 - mae: 2.7814 - learning_rate: 0.0042
Epoch 53/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 682us/step - loss: 15.2915 - mae: 2.7894 - learning_rate: 0.0042
Epoch 54/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 596us/step - loss: 14.5496 - mae: 2.7226 - learning_rate: 0.0042
Epoch 55/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 631us/step - loss: 15.4462 - mae: 2.8069 - learning_rate: 0.0042
Epoch 56/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - loss: 14.0482 - mae: 2.6577 - learning_rate: 0.0021
Epoch 57/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 676us/step - loss: 14.0790 - mae: 2.6414 - learning_rate: 0.0021
Epoch 58/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 571us/step - loss: 13.4468 - mae: 2.5937 - learning_rate: 0.0021
Epoch 59/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 573us/step - loss: 13.3244 - mae: 2.5947 - learning_rate: 0.0021
Epoch 60/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 565us/step - loss: 13.6454 - mae: 2.6110 - learning_rate: 0.0021
Epoch 61/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 626us/step - loss: 13.2182 - mae: 2.5776 - learning_rate: 0.0021
Epoch 62/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 575us/step - loss: 13.6214 - mae: 2.5923 - learning_rate: 0.0021
Epoch 63/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 574us/step - loss: 13.4411 - mae: 2.5824 - learning_rate: 0.0021
Epoch 64/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 648us/step - loss: 13.6174 - mae: 2.6000 - learning_rate: 0.0021
Epoch 65/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 690us/step - loss: 13.3266 - mae: 2.5761 - learning_rate: 0.0021
Epoch 66/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 586us/step - loss: 13.1143 - mae: 2.5741 - learning_rate: 0.0021
Epoch 67/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 582us/step - loss: 13.0542 - mae: 2.5648 - learning_rate: 0.0021
Epoch 68/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - loss: 13.2816 - mae: 2.5607 - learning_rate: 0.0021
Epoch 69/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 621us/step - loss: 12.6420 - mae: 2.5565 - learning_rate: 0.0021
Epoch 70/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 603us/step - loss: 12.8267 - mae: 2.5423 - learning_rate: 0.0021
Epoch 71/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 573us/step - loss: 13.1158 - mae: 2.5767 - learning_rate: 0.0021
Epoch 72/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - loss: 13.2311 - mae: 2.5783 - learning_rate: 0.0021
Epoch 73/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 576us/step - loss: 13.1090 - mae: 2.5700 - learning_rate: 0.0021
Epoch 74/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 578us/step - loss: 12.6864 - mae: 2.5372 - learning_rate: 0.0021
Epoch 75/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 650us/step - loss: 12.8203 - mae: 2.5117 - learning_rate: 0.0010
Epoch 76/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 579us/step - loss: 12.5158 - mae: 2.4948 - learning_rate: 0.0010
Epoch 77/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 571us/step - loss: 11.6903 - mae: 2.4350 - learning_rate: 0.0010
Epoch 78/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 624us/step - loss: 12.4868 - mae: 2.4821 - learning_rate: 0.0010
Epoch 79/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 586us/step - loss: 12.0512 - mae: 2.4662 - learning_rate: 0.0010
Epoch 80/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 574us/step - loss: 11.8401 - mae: 2.4437 - learning_rate: 0.0010
Epoch 81/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 646us/step - loss: 12.1533 - mae: 2.4613 - learning_rate: 0.0010
Epoch 82/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 617us/step - loss: 11.9567 - mae: 2.4519 - learning_rate: 0.0010
Epoch 83/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 640us/step - loss: 12.1998 - mae: 2.4481 - learning_rate: 5.1910e-04
Epoch 84/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 610us/step - loss: 11.9686 - mae: 2.4497 - learning_rate: 5.1910e-04
Epoch 85/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 631us/step - loss: 11.9390 - mae: 2.4355 - learning_rate: 5.1910e-04
Epoch 86/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - loss: 12.0521 - mae: 2.4392 - learning_rate: 5.1910e-04
Epoch 87/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - loss: 11.7368 - mae: 2.4080 - learning_rate: 5.1910e-04
Epoch 88/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 690us/step - loss: 11.9449 - mae: 2.4455 - learning_rate: 5.1910e-04
Epoch 89/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 570us/step - loss: 11.6033 - mae: 2.4189 - learning_rate: 5.1910e-04
Epoch 90/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 567us/step - loss: 11.8749 - mae: 2.4287 - learning_rate: 5.1910e-04
Epoch 91/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - loss: 11.7666 - mae: 2.4018 - learning_rate: 5.1910e-04
Epoch 92/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 583us/step - loss: 12.0481 - mae: 2.4290 - learning_rate: 5.1910e-04
Epoch 93/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 715us/step - loss: 11.4935 - mae: 2.3934 - learning_rate: 2.5955e-04
Epoch 94/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 595us/step - loss: 11.3888 - mae: 2.3689 - learning_rate: 2.5955e-04
Epoch 95/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - loss: 11.6982 - mae: 2.4184 - learning_rate: 2.5955e-04
Epoch 96/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 598us/step - loss: 11.2675 - mae: 2.3594 - learning_rate: 2.5955e-04
Epoch 97/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 584us/step - loss: 11.6034 - mae: 2.4043 - learning_rate: 2.5955e-04
Epoch 98/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 719us/step - loss: 11.8049 - mae: 2.4116 - learning_rate: 2.5955e-04
Epoch 99/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 680us/step - loss: 11.1182 - mae: 2.3596 - learning_rate: 2.5955e-04
Epoch 100/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 661us/step - loss: 11.3439 - mae: 2.3817 - learning_rate: 2.5955e-04
274/274 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step
Submission saved: /Users/m0122wt/Desktop/02.プライベート/01.ノウハウ/07.データ分析/notebook/signate_smbc_202506/data/submission/submission_nn_20250630_003938.csv
CPU times: user 3h 1min 6s, sys: 20min 55s, total: 3h 22min 2s
Wall time: 5h 14min 58s

### 履歴
___
LIGHTGBM：ベイズ最適化の結果
Best params: {'num_leaves': 20, 'learning_rate': 0.07056499143559153, 'feature_fraction': 0.930666633751073, 'bagging_fraction': 0.8764523692423547, 'bagging_freq': 9, 'min_child_samples': 35, 'objective': 'regression', 'metric': 'rmse', 'boosting_type': 'gbdt', 'verbose': -1, 'random_state': 42}  
Best CV RMSE: 2.517122779389563  
Selected features: 73/92  
___
NEURAL_NETWORK：ベイズ最適化の結果
Best params: {'layer1_units': 48, 'layer2_units': 121, 'layer3_units': 8, 'dropout_rate': 0.16207371516723865, 'learning_rate': 0.005173979484789956, 'batch_size': 16}  
Best CV RMSE: 3.7179227519163134  
___
NEURAL_NETWORK：ベイズ最適化の結果
Best params: {'layer1_units': 121, 'layer2_units': 59, 'layer3_units': 54, 'dropout_rate': 0.13383472933292856, 'learning_rate': 0.00830555831035743, 'batch_size': 16, 'hidden_layers': [121, 59, 54], 'epochs': 100, 'patience': 10}  
Best CV RMSE: 3.5697693374659956  
___

In [ ]:
predictions

array([11.300329, 12.014666, 12.260893, ..., 20.831654, 20.7573  ,
       20.324287], dtype=float32)

In [ ]:
%%time

filename_sequential = 'submission_nn_sequential'

# 逐次予測（ラグ特徴量を考慮）
model_sequential, predictions_sequential = train_and_predict(
    model_type='neural_network',
    train_df=train,
    test_df=test,
    target_col='price_actual',
    optimize=True,
    sequential=True,  # 逐次予測
    output_path=SUBMISSION,
    filename=filename_sequential
)

[I 2025-06-29 16:16:17,234] A new study created in memory with name: no-name-50bb1049-8f21-4195-a625-62b95eff998c

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step

[I 2025-06-29 16:18:38,151] Trial 0 finished with value: 5.074263028514065 and parameters: {'layer1_units': 231, 'layer2_units': 119, 'layer3_units': 41, 'dropout_rate': 0.45816053802580203, 'learning_rate': 0.0017795345905176271, 'batch_size': 16}. Best is trial 0 with value: 5.074263028514065.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step

[I 2025-06-29 16:21:10,988] Trial 1 finished with value: 4.793218494337585 and parameters: {'layer1_units': 72, 'layer2_units': 85, 'layer3_units': 8, 'dropout_rate': 0.3424013268551534, 'learning_rate': 0.007644347243250683, 'batch_size': 16}. Best is trial 1 with value: 4.793218494337585.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step

[I 2025-06-29 16:22:53,182] Trial 2 finished with value: 6.181810953841236 and parameters: {'layer1_units': 42, 'layer2_units': 18, 'layer3_units': 39, 'dropout_rate': 0.44576777895251607, 'learning_rate': 0.003557387568070253, 'batch_size': 16}. Best is trial 1 with value: 4.793218494337585.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step

[I 2025-06-29 16:24:29,077] Trial 3 finished with value: 4.200605622605982 and parameters: {'layer1_units': 101, 'layer2_units': 18, 'layer3_units': 28, 'dropout_rate': 0.24443577352425724, 'learning_rate': 0.009254430469100386, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step

[I 2025-06-29 16:25:38,968] Trial 4 finished with value: 5.713271409081391 and parameters: {'layer1_units': 188, 'layer2_units': 106, 'layer3_units': 14, 'dropout_rate': 0.3284372308853414, 'learning_rate': 0.0005825499654002242, 'batch_size': 32}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step

[I 2025-06-29 16:27:14,756] Trial 5 finished with value: 4.510507254787202 and parameters: {'layer1_units': 84, 'layer2_units': 34, 'layer3_units': 58, 'dropout_rate': 0.2151765746589791, 'learning_rate': 0.009645845894078074, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step

[I 2025-06-29 16:28:38,271] Trial 6 finished with value: 5.316474290228831 and parameters: {'layer1_units': 217, 'layer2_units': 62, 'layer3_units': 21, 'dropout_rate': 0.1038225547174335, 'learning_rate': 0.0006752547941877406, 'batch_size': 32}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step

[I 2025-06-29 16:30:46,118] Trial 7 finished with value: 5.044489814408023 and parameters: {'layer1_units': 247, 'layer2_units': 67, 'layer3_units': 49, 'dropout_rate': 0.2928040201066733, 'learning_rate': 0.0016928893760835395, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step

[I 2025-06-29 16:32:38,015] Trial 8 finished with value: 5.696168508024507 and parameters: {'layer1_units': 214, 'layer2_units': 63, 'layer3_units': 8, 'dropout_rate': 0.3342820115766887, 'learning_rate': 0.002312966558592089, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step

[I 2025-06-29 16:33:27,810] Trial 9 finished with value: 6.379744267447819 and parameters: {'layer1_units': 67, 'layer2_units': 79, 'layer3_units': 8, 'dropout_rate': 0.14243901217802324, 'learning_rate': 0.0005921992607495194, 'batch_size': 64}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step

[I 2025-06-29 16:34:26,315] Trial 10 finished with value: 6.640201905444121 and parameters: {'layer1_units': 134, 'layer2_units': 43, 'layer3_units': 28, 'dropout_rate': 0.21511722331783228, 'learning_rate': 0.0001380342605887115, 'batch_size': 64}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step

[I 2025-06-29 16:36:07,342] Trial 11 finished with value: 4.404029043592274 and parameters: {'layer1_units': 123, 'layer2_units': 18, 'layer3_units': 63, 'dropout_rate': 0.22135081453025682, 'learning_rate': 0.009841297712717545, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step

[I 2025-06-29 16:37:47,589] Trial 12 finished with value: 4.709769056426931 and parameters: {'layer1_units': 127, 'layer2_units': 16, 'layer3_units': 62, 'dropout_rate': 0.23178976654729386, 'learning_rate': 0.005216397810282644, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step

[I 2025-06-29 16:40:24,854] Trial 13 finished with value: 3.8802684336887294 and parameters: {'layer1_units': 160, 'layer2_units': 38, 'layer3_units': 27, 'dropout_rate': 0.26200507726198113, 'learning_rate': 0.0048079838507547245, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step

[I 2025-06-29 16:41:02,968] Trial 14 finished with value: 5.437306404252508 and parameters: {'layer1_units': 171, 'layer2_units': 40, 'layer3_units': 29, 'dropout_rate': 0.3946165704009317, 'learning_rate': 0.00374890968649295, 'batch_size': 64}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step

[I 2025-06-29 16:42:24,088] Trial 15 finished with value: 5.681424358700821 and parameters: {'layer1_units': 102, 'layer2_units': 48, 'layer3_units': 28, 'dropout_rate': 0.28092905037690025, 'learning_rate': 0.0002098117602848322, 'batch_size': 32}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 16:44:21,883] Trial 16 finished with value: 3.9842364681282434 and parameters: {'layer1_units': 163, 'layer2_units': 29, 'layer3_units': 20, 'dropout_rate': 0.16839202032287665, 'learning_rate': 0.005032049839442836, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step

[I 2025-06-29 16:46:24,817] Trial 17 finished with value: 4.671457806194619 and parameters: {'layer1_units': 170, 'layer2_units': 31, 'layer3_units': 19, 'dropout_rate': 0.15223687943054448, 'learning_rate': 0.0010848851901907016, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step

[I 2025-06-29 16:48:05,503] Trial 18 finished with value: 4.987303459980753 and parameters: {'layer1_units': 159, 'layer2_units': 51, 'layer3_units': 21, 'dropout_rate': 0.16526270057109949, 'learning_rate': 0.004641146913641022, 'batch_size': 32}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step

[I 2025-06-29 16:49:03,864] Trial 19 finished with value: 4.798873074783791 and parameters: {'layer1_units': 198, 'layer2_units': 97, 'layer3_units': 33, 'dropout_rate': 0.16933152769087334, 'learning_rate': 0.0024831091412395217, 'batch_size': 64}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step

[I 2025-06-29 16:50:46,944] Trial 20 finished with value: 4.803532446333111 and parameters: {'layer1_units': 154, 'layer2_units': 29, 'layer3_units': 46, 'dropout_rate': 0.10556135701752106, 'learning_rate': 0.0002826800896007474, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step

[I 2025-06-29 16:52:31,332] Trial 21 finished with value: 3.876923587097753 and parameters: {'layer1_units': 104, 'layer2_units': 27, 'layer3_units': 24, 'dropout_rate': 0.2521833960188156, 'learning_rate': 0.006747799457784578, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 16:54:19,683] Trial 22 finished with value: 4.098280266226412 and parameters: {'layer1_units': 141, 'layer2_units': 52, 'layer3_units': 16, 'dropout_rate': 0.2643419750033902, 'learning_rate': 0.006036223373022402, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step

[I 2025-06-29 16:55:45,860] Trial 23 finished with value: 4.583354773497168 and parameters: {'layer1_units': 107, 'layer2_units': 29, 'layer3_units': 24, 'dropout_rate': 0.17970070470048177, 'learning_rate': 0.0031012207899636214, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step

[I 2025-06-29 16:57:31,833] Trial 24 finished with value: 4.057573024445409 and parameters: {'layer1_units': 186, 'layer2_units': 37, 'layer3_units': 34, 'dropout_rate': 0.36769744404441457, 'learning_rate': 0.00677390702794368, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step

[I 2025-06-29 16:59:20,890] Trial 25 finished with value: 3.903484769553708 and parameters: {'layer1_units': 148, 'layer2_units': 27, 'layer3_units': 16, 'dropout_rate': 0.2618145878335157, 'learning_rate': 0.004914964000322214, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

[I 2025-06-29 17:01:03,357] Trial 26 finished with value: 5.555649008698103 and parameters: {'layer1_units': 38, 'layer2_units': 55, 'layer3_units': 14, 'dropout_rate': 0.3118908687527547, 'learning_rate': 0.0013604553489171085, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step

[I 2025-06-29 17:02:45,237] Trial 27 finished with value: 4.614513411350089 and parameters: {'layer1_units': 117, 'layer2_units': 25, 'layer3_units': 25, 'dropout_rate': 0.26262291868517645, 'learning_rate': 0.0027491794202358522, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 528us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step

[I 2025-06-29 17:03:25,022] Trial 28 finished with value: 5.521591752906142 and parameters: {'layer1_units': 144, 'layer2_units': 40, 'layer3_units': 16, 'dropout_rate': 0.4104880965800561, 'learning_rate': 0.006872342470003896, 'batch_size': 64}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step

[I 2025-06-29 17:04:52,936] Trial 29 finished with value: 5.130221208960801 and parameters: {'layer1_units': 90, 'layer2_units': 75, 'layer3_units': 37, 'dropout_rate': 0.19700434082368723, 'learning_rate': 0.001959391708264458, 'batch_size': 32}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 17:07:17,525] Trial 30 finished with value: 4.942246008915619 and parameters: {'layer1_units': 60, 'layer2_units': 46, 'layer3_units': 33, 'dropout_rate': 0.2611281437285348, 'learning_rate': 0.003952905051667406, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step

[I 2025-06-29 17:09:38,594] Trial 31 finished with value: 4.388172100269233 and parameters: {'layer1_units': 160, 'layer2_units': 128, 'layer3_units': 24, 'dropout_rate': 0.29863958929469125, 'learning_rate': 0.0053434046885266805, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step

[I 2025-06-29 17:11:48,721] Trial 32 finished with value: 3.966196444394572 and parameters: {'layer1_units': 172, 'layer2_units': 24, 'layer3_units': 19, 'dropout_rate': 0.19198681737751772, 'learning_rate': 0.004745872964637229, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step

[I 2025-06-29 17:13:24,956] Trial 33 finished with value: 4.848623228139817 and parameters: {'layer1_units': 187, 'layer2_units': 24, 'layer3_units': 13, 'dropout_rate': 0.48715771258717167, 'learning_rate': 0.007347413278312054, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step

[I 2025-06-29 17:15:40,634] Trial 34 finished with value: 4.2220808814206645 and parameters: {'layer1_units': 141, 'layer2_units': 24, 'layer3_units': 11, 'dropout_rate': 0.20025985254694414, 'learning_rate': 0.0038729417171148865, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step

[I 2025-06-29 17:17:44,940] Trial 35 finished with value: 4.512844546416352 and parameters: {'layer1_units': 178, 'layer2_units': 34, 'layer3_units': 19, 'dropout_rate': 0.25763390868707475, 'learning_rate': 0.003172223050558643, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step

[I 2025-06-29 17:19:19,493] Trial 36 finished with value: 4.362338230267158 and parameters: {'layer1_units': 202, 'layer2_units': 22, 'layer3_units': 41, 'dropout_rate': 0.3495540925529042, 'learning_rate': 0.007813265382854321, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step

[I 2025-06-29 17:21:06,339] Trial 37 finished with value: 4.819765828262423 and parameters: {'layer1_units': 87, 'layer2_units': 58, 'layer3_units': 30, 'dropout_rate': 0.23416161933560936, 'learning_rate': 0.0017032590013533627, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step

[I 2025-06-29 17:23:06,335] Trial 38 finished with value: 5.498987794441444 and parameters: {'layer1_units': 114, 'layer2_units': 94, 'layer3_units': 25, 'dropout_rate': 0.31413125354794474, 'learning_rate': 0.0008784677191219725, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step

[I 2025-06-29 17:24:14,044] Trial 39 finished with value: 5.424504141513313 and parameters: {'layer1_units': 231, 'layer2_units': 35, 'layer3_units': 16, 'dropout_rate': 0.24518404482570433, 'learning_rate': 0.0004263210687753897, 'batch_size': 32}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step

[I 2025-06-29 17:25:36,563] Trial 40 finished with value: 4.526995081993984 and parameters: {'layer1_units': 131, 'layer2_units': 18, 'layer3_units': 23, 'dropout_rate': 0.27470656962423273, 'learning_rate': 0.008149996837600442, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step

[I 2025-06-29 17:27:12,893] Trial 41 finished with value: 4.298458958047966 and parameters: {'layer1_units': 163, 'layer2_units': 27, 'layer3_units': 19, 'dropout_rate': 0.13368977959399322, 'learning_rate': 0.004934358063487169, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step

[I 2025-06-29 17:29:03,749] Trial 42 finished with value: 3.803042084025541 and parameters: {'layer1_units': 152, 'layer2_units': 32, 'layer3_units': 21, 'dropout_rate': 0.2084003783040671, 'learning_rate': 0.004209882321912923, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step

[I 2025-06-29 17:30:57,451] Trial 43 finished with value: 4.32770487822272 and parameters: {'layer1_units': 177, 'layer2_units': 44, 'layer3_units': 11, 'dropout_rate': 0.19890986854622472, 'learning_rate': 0.004048376954738159, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step

[I 2025-06-29 17:32:25,382] Trial 44 finished with value: 4.535062081732334 and parameters: {'layer1_units': 154, 'layer2_units': 37, 'layer3_units': 27, 'dropout_rate': 0.23951964483520002, 'learning_rate': 0.0022609258738724492, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step

[I 2025-06-29 17:34:05,452] Trial 45 finished with value: 4.36564886470922 and parameters: {'layer1_units': 145, 'layer2_units': 21, 'layer3_units': 17, 'dropout_rate': 0.21249795584279516, 'learning_rate': 0.0059039903646179795, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step

[I 2025-06-29 17:34:48,825] Trial 46 finished with value: 4.973814029113038 and parameters: {'layer1_units': 151, 'layer2_units': 32, 'layer3_units': 31, 'dropout_rate': 0.1862350509185439, 'learning_rate': 0.008582523127940705, 'batch_size': 64}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step

[I 2025-06-29 17:36:55,612] Trial 47 finished with value: 4.561239355043058 and parameters: {'layer1_units': 199, 'layer2_units': 69, 'layer3_units': 22, 'dropout_rate': 0.2817386115484715, 'learning_rate': 0.003385431189179845, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 722us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step

[I 2025-06-29 17:38:33,653] Trial 48 finished with value: 4.673116698811078 and parameters: {'layer1_units': 57, 'layer2_units': 41, 'layer3_units': 11, 'dropout_rate': 0.22059134477736497, 'learning_rate': 0.004486025587065181, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step

[I 2025-06-29 17:39:21,408] Trial 49 finished with value: 5.08159676717027 and parameters: {'layer1_units': 124, 'layer2_units': 20, 'layer3_units': 26, 'dropout_rate': 0.2463180230812178, 'learning_rate': 0.009694909443547372, 'batch_size': 32}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step

[I 2025-06-29 17:41:07,598] Trial 50 finished with value: 4.718164594689419 and parameters: {'layer1_units': 135, 'layer2_units': 111, 'layer3_units': 22, 'dropout_rate': 0.2902434595777824, 'learning_rate': 0.002811870655888536, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step

[I 2025-06-29 17:42:38,182] Trial 51 finished with value: 4.935956199035067 and parameters: {'layer1_units': 169, 'layer2_units': 16, 'layer3_units': 19, 'dropout_rate': 0.16113651003893667, 'learning_rate': 0.0060287579208341685, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step

[I 2025-06-29 17:44:25,679] Trial 52 finished with value: 3.7263147637636926 and parameters: {'layer1_units': 166, 'layer2_units': 28, 'layer3_units': 21, 'dropout_rate': 0.18465732545534394, 'learning_rate': 0.005130699341029796, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step

[I 2025-06-29 17:46:15,472] Trial 53 finished with value: 3.914639503050824 and parameters: {'layer1_units': 178, 'layer2_units': 31, 'layer3_units': 17, 'dropout_rate': 0.12953610708734467, 'learning_rate': 0.004274443663234082, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step

[I 2025-06-29 17:48:03,633] Trial 54 finished with value: 4.51969006860322 and parameters: {'layer1_units': 207, 'layer2_units': 32, 'layer3_units': 14, 'dropout_rate': 0.1510204527833651, 'learning_rate': 0.0020662009470407273, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step

[I 2025-06-29 17:49:02,648] Trial 55 finished with value: 6.0212717828632485 and parameters: {'layer1_units': 187, 'layer2_units': 48, 'layer3_units': 21, 'dropout_rate': 0.12853049601334154, 'learning_rate': 0.00010861522753246053, 'batch_size': 64}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step

[I 2025-06-29 17:50:09,684] Trial 56 finished with value: 4.752262772883124 and parameters: {'layer1_units': 179, 'layer2_units': 38, 'layer3_units': 52, 'dropout_rate': 0.10561130256172456, 'learning_rate': 0.001408799391326356, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step

[I 2025-06-29 17:51:49,013] Trial 57 finished with value: 4.271680300673288 and parameters: {'layer1_units': 151, 'layer2_units': 27, 'layer3_units': 17, 'dropout_rate': 0.11737909999904425, 'learning_rate': 0.006226030107425921, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step

[I 2025-06-29 17:53:42,345] Trial 58 finished with value: 4.541122768570439 and parameters: {'layer1_units': 136, 'layer2_units': 85, 'layer3_units': 8, 'dropout_rate': 0.2119074665734736, 'learning_rate': 0.004252683490705679, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step

[I 2025-06-29 17:54:29,091] Trial 59 finished with value: 5.320402546570993 and parameters: {'layer1_units': 76, 'layer2_units': 32, 'layer3_units': 28, 'dropout_rate': 0.3219982845665436, 'learning_rate': 0.003412185894938846, 'batch_size': 32}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step

[I 2025-06-29 17:56:06,799] Trial 60 finished with value: 4.632603281569516 and parameters: {'layer1_units': 165, 'layer2_units': 43, 'layer3_units': 31, 'dropout_rate': 0.17838094107157404, 'learning_rate': 0.0026559489785809437, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step

[I 2025-06-29 17:58:35,339] Trial 61 finished with value: 4.051974174172424 and parameters: {'layer1_units': 173, 'layer2_units': 28, 'layer3_units': 18, 'dropout_rate': 0.22596753733763658, 'learning_rate': 0.005392255419772543, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step

[I 2025-06-29 18:00:29,454] Trial 62 finished with value: 3.855244056736119 and parameters: {'layer1_units': 156, 'layer2_units': 21, 'layer3_units': 12, 'dropout_rate': 0.19732603651916986, 'learning_rate': 0.004765225879721293, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step

[I 2025-06-29 18:02:16,732] Trial 63 finished with value: 4.204696317639331 and parameters: {'layer1_units': 155, 'layer2_units': 20, 'layer3_units': 13, 'dropout_rate': 0.25018385515405483, 'learning_rate': 0.0069318952883786564, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step

[I 2025-06-29 18:03:49,577] Trial 64 finished with value: 4.337134652083778 and parameters: {'layer1_units': 193, 'layer2_units': 35, 'layer3_units': 10, 'dropout_rate': 0.26958467219260107, 'learning_rate': 0.005639888448649563, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step

[I 2025-06-29 18:05:24,015] Trial 65 finished with value: 4.162228320398476 and parameters: {'layer1_units': 95, 'layer2_units': 30, 'layer3_units': 15, 'dropout_rate': 0.14865918411366855, 'learning_rate': 0.003647193397089965, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 18:06:01,280] Trial 66 finished with value: 5.273743167793875 and parameters: {'layer1_units': 148, 'layer2_units': 26, 'layer3_units': 23, 'dropout_rate': 0.20522938092354384, 'learning_rate': 0.004995582237806727, 'batch_size': 64}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step

[I 2025-06-29 18:07:52,988] Trial 67 finished with value: 4.043202183926007 and parameters: {'layer1_units': 117, 'layer2_units': 16, 'layer3_units': 21, 'dropout_rate': 0.22905827318428648, 'learning_rate': 0.008767070319985084, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step

[I 2025-06-29 18:09:54,375] Trial 68 finished with value: 4.441241004857822 and parameters: {'layer1_units': 160, 'layer2_units': 39, 'layer3_units': 14, 'dropout_rate': 0.17439516117153217, 'learning_rate': 0.0030103585212519816, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2025-06-29 18:11:51,001] Trial 69 finished with value: 4.220224826896633 and parameters: {'layer1_units': 140, 'layer2_units': 22, 'layer3_units': 25, 'dropout_rate': 0.18529852162063604, 'learning_rate': 0.004383271603838077, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step

[I 2025-06-29 18:14:15,126] Trial 70 finished with value: 3.9131605365559787 and parameters: {'layer1_units': 128, 'layer2_units': 50, 'layer3_units': 36, 'dropout_rate': 0.13598651366493703, 'learning_rate': 0.007060185115828829, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step

[I 2025-06-29 18:16:01,243] Trial 71 finished with value: 4.018200739942159 and parameters: {'layer1_units': 105, 'layer2_units': 49, 'layer3_units': 36, 'dropout_rate': 0.1330120518896429, 'learning_rate': 0.007384608055971709, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step

[I 2025-06-29 18:17:37,636] Trial 72 finished with value: 4.009044774832619 and parameters: {'layer1_units': 126, 'layer2_units': 33, 'layer3_units': 42, 'dropout_rate': 0.2866789881189658, 'learning_rate': 0.006533750759084934, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step

[I 2025-06-29 18:19:42,847] Trial 73 finished with value: 4.046635675109748 and parameters: {'layer1_units': 111, 'layer2_units': 53, 'layer3_units': 48, 'dropout_rate': 0.16198912274893296, 'learning_rate': 0.005469986190755728, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step

[I 2025-06-29 18:21:43,522] Trial 74 finished with value: 4.426368342782121 and parameters: {'layer1_units': 181, 'layer2_units': 62, 'layer3_units': 44, 'dropout_rate': 0.12112609993278722, 'learning_rate': 0.0037802175079265973, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step

[I 2025-06-29 18:23:34,610] Trial 75 finished with value: 4.030246036999375 and parameters: {'layer1_units': 167, 'layer2_units': 45, 'layer3_units': 38, 'dropout_rate': 0.13954871958332854, 'learning_rate': 0.007768766480780474, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step

[I 2025-06-29 18:25:36,673] Trial 76 finished with value: 4.322982682060346 and parameters: {'layer1_units': 99, 'layer2_units': 36, 'layer3_units': 20, 'dropout_rate': 0.2344462089884563, 'learning_rate': 0.0048696750945942495, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step

[I 2025-06-29 18:26:38,364] Trial 77 finished with value: 4.374680156357334 and parameters: {'layer1_units': 129, 'layer2_units': 24, 'layer3_units': 17, 'dropout_rate': 0.15756959928807987, 'learning_rate': 0.006552035784015933, 'batch_size': 32}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step

[I 2025-06-29 18:28:41,693] Trial 78 finished with value: 4.202513930651106 and parameters: {'layer1_units': 157, 'layer2_units': 57, 'layer3_units': 53, 'dropout_rate': 0.19011698782595582, 'learning_rate': 0.004293105439608704, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[I 2025-06-29 18:30:14,953] Trial 79 finished with value: 5.470211217011585 and parameters: {'layer1_units': 145, 'layer2_units': 41, 'layer3_units': 12, 'dropout_rate': 0.3013317430471451, 'learning_rate': 0.0023791810493400873, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step

[I 2025-06-29 18:31:03,062] Trial 80 finished with value: 4.50581828221028 and parameters: {'layer1_units': 118, 'layer2_units': 30, 'layer3_units': 27, 'dropout_rate': 0.25488495409047873, 'learning_rate': 0.008970350676271529, 'batch_size': 64}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step

[I 2025-06-29 18:32:57,883] Trial 81 finished with value: 4.556316378905488 and parameters: {'layer1_units': 169, 'layer2_units': 22, 'layer3_units': 23, 'dropout_rate': 0.20778279395441276, 'learning_rate': 0.004739519697556498, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step

[I 2025-06-29 18:34:41,903] Trial 82 finished with value: 3.964315292896854 and parameters: {'layer1_units': 175, 'layer2_units': 26, 'layer3_units': 20, 'dropout_rate': 0.19652030719281052, 'learning_rate': 0.0033640381370640005, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 18:36:51,816] Trial 83 finished with value: 4.124833441502935 and parameters: {'layer1_units': 193, 'layer2_units': 28, 'layer3_units': 15, 'dropout_rate': 0.21818996325721757, 'learning_rate': 0.0034895238243873106, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step

[I 2025-06-29 18:38:47,422] Trial 84 finished with value: 4.254131244188945 and parameters: {'layer1_units': 174, 'layer2_units': 25, 'layer3_units': 9, 'dropout_rate': 0.17428789224304472, 'learning_rate': 0.00578584288821937, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step

[I 2025-06-29 18:40:52,347] Trial 85 finished with value: 4.451758667939287 and parameters: {'layer1_units': 160, 'layer2_units': 34, 'layer3_units': 18, 'dropout_rate': 0.2741335643755298, 'learning_rate': 0.003101290631913158, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step

[I 2025-06-29 18:42:56,050] Trial 86 finished with value: 4.70565759146311 and parameters: {'layer1_units': 138, 'layer2_units': 18, 'layer3_units': 20, 'dropout_rate': 0.10149768451109416, 'learning_rate': 0.007038852708420911, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step

[I 2025-06-29 18:44:31,077] Trial 87 finished with value: 5.505263088588185 and parameters: {'layer1_units': 181, 'layer2_units': 29, 'layer3_units': 34, 'dropout_rate': 0.19629086257359998, 'learning_rate': 0.004034739450897407, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step

[I 2025-06-29 18:47:28,546] Trial 88 finished with value: 4.373285917328957 and parameters: {'layer1_units': 153, 'layer2_units': 37, 'layer3_units': 26, 'dropout_rate': 0.1215205905565015, 'learning_rate': 0.005049395001383762, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step

[I 2025-06-29 18:48:57,218] Trial 89 finished with value: 4.485887912986675 and parameters: {'layer1_units': 164, 'layer2_units': 20, 'layer3_units': 22, 'dropout_rate': 0.236870839694781, 'learning_rate': 0.007815723216115506, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 18:50:26,689] Trial 90 finished with value: 4.864176882123172 and parameters: {'layer1_units': 133, 'layer2_units': 42, 'layer3_units': 24, 'dropout_rate': 0.14440074687092982, 'learning_rate': 0.004463348259339028, 'batch_size': 32}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step

[I 2025-06-29 18:53:14,446] Trial 91 finished with value: 4.399429848063427 and parameters: {'layer1_units': 173, 'layer2_units': 24, 'layer3_units': 19, 'dropout_rate': 0.19136492158775065, 'learning_rate': 0.006015838418824439, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 736us/step

[I 2025-06-29 18:55:37,254] Trial 92 finished with value: 4.251467600414921 and parameters: {'layer1_units': 184, 'layer2_units': 26, 'layer3_units': 16, 'dropout_rate': 0.21545559324585026, 'learning_rate': 0.009998311670395953, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step

[I 2025-06-29 18:57:59,582] Trial 93 finished with value: 5.353030791510767 and parameters: {'layer1_units': 148, 'layer2_units': 30, 'layer3_units': 18, 'dropout_rate': 0.18272019332434597, 'learning_rate': 0.0003056971180607072, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step

[I 2025-06-29 19:00:31,612] Trial 94 finished with value: 4.234572988546891 and parameters: {'layer1_units': 211, 'layer2_units': 23, 'layer3_units': 29, 'dropout_rate': 0.1688142748853959, 'learning_rate': 0.005441476839108579, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 699us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step

[I 2025-06-29 19:02:25,336] Trial 95 finished with value: 4.14581189730052 and parameters: {'layer1_units': 80, 'layer2_units': 19, 'layer3_units': 20, 'dropout_rate': 0.20478635459715497, 'learning_rate': 0.00372041379659297, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 651us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step

[I 2025-06-29 19:04:13,552] Trial 96 finished with value: 5.298908634476747 and parameters: {'layer1_units': 191, 'layer2_units': 32, 'layer3_units': 13, 'dropout_rate': 0.22434216663593498, 'learning_rate': 0.0008167649703072617, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step

[I 2025-06-29 19:06:40,575] Trial 97 finished with value: 4.428813521271879 and parameters: {'layer1_units': 158, 'layer2_units': 27, 'layer3_units': 21, 'dropout_rate': 0.24433243894669238, 'learning_rate': 0.004748594920786143, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 635us/step

[I 2025-06-29 19:09:02,502] Trial 98 finished with value: 4.898368358090074 and parameters: {'layer1_units': 175, 'layer2_units': 39, 'layer3_units': 15, 'dropout_rate': 0.4468446909021021, 'learning_rate': 0.002900537960298865, 'batch_size': 16}. Best is trial 52 with value: 3.7263147637636926.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 669us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step

[I 2025-06-29 19:09:50,689] Trial 99 finished with value: 5.024153471111929 and parameters: {'layer1_units': 166, 'layer2_units': 36, 'layer3_units': 24, 'dropout_rate': 0.2663935755146651, 'learning_rate': 0.0033109105067564946, 'batch_size': 64}. Best is trial 52 with value: 3.7263147637636926.

NEURAL_NETWORK：ベイズ最適化の結果
Best params: {'layer1_units': 166, 'layer2_units': 28, 'layer3_units': 21, 'dropout_rate': 0.18465732545534394, 'learning_rate': 0.005130699341029796, 'batch_size': 16, 'hidden_layers': [166, 28, 21], 'epochs': 100, 'patience': 10}
Best CV RMSE: 3.7263147637636926
Epoch 1/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 3s 705us/step - loss: 344.9158 - mae: 13.4244 - learning_rate: 0.0051
Epoch 2/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 657us/step - loss: 138.5943 - mae: 9.2299 - learning_rate: 0.0051
Epoch 3/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - loss: 108.5467 - mae: 8.1162 - learning_rate: 0.0051
Epoch 4/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 661us/step - loss: 85.6584 - mae: 7.1422 - learning_rate: 0.0051
Epoch 5/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 647us/step - loss: 73.7934 - mae: 6.6012 - learning_rate: 0.0051
Epoch 6/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 729us/step - loss: 63.3315 - mae: 6.1246 - learning_rate: 0.0051
Epoch 7/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 946us/step - loss: 53.2762 - mae: 5.6240 - learning_rate: 0.0051
Epoch 8/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - loss: 50.2145 - mae: 5.4125 - learning_rate: 0.0051
Epoch 9/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - loss: 43.2281 - mae: 5.0307 - learning_rate: 0.0051
Epoch 10/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 686us/step - loss: 40.3486 - mae: 4.8571 - learning_rate: 0.0051
Epoch 11/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - loss: 38.4373 - mae: 4.7324 - learning_rate: 0.0051
Epoch 12/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 878us/step - loss: 33.8300 - mae: 4.4477 - learning_rate: 0.0051
Epoch 13/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 680us/step - loss: 32.7342 - mae: 4.3540 - learning_rate: 0.0051
Epoch 14/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - loss: 32.1181 - mae: 4.3113 - learning_rate: 0.0051
Epoch 15/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - loss: 32.0021 - mae: 4.2587 - learning_rate: 0.0051
Epoch 16/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 630us/step - loss: 31.9555 - mae: 4.2805 - learning_rate: 0.0051
Epoch 17/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 729us/step - loss: 31.0034 - mae: 4.1973 - learning_rate: 0.0051
Epoch 18/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 627us/step - loss: 31.7527 - mae: 4.2344 - learning_rate: 0.0051
Epoch 19/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 646us/step - loss: 30.7464 - mae: 4.1517 - learning_rate: 0.0051
Epoch 20/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - loss: 31.0629 - mae: 4.1660 - learning_rate: 0.0051
Epoch 21/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - loss: 31.5548 - mae: 4.2110 - learning_rate: 0.0051
Epoch 22/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 666us/step - loss: 31.4917 - mae: 4.1827 - learning_rate: 0.0051
Epoch 23/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - loss: 28.7896 - mae: 4.0020 - learning_rate: 0.0026
Epoch 24/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 980us/step - loss: 28.8311 - mae: 3.9920 - learning_rate: 0.0026
Epoch 25/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 864us/step - loss: 28.2256 - mae: 3.9479 - learning_rate: 0.0026
Epoch 26/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 643us/step - loss: 28.3396 - mae: 3.9716 - learning_rate: 0.0026
Epoch 27/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - loss: 28.1321 - mae: 3.9717 - learning_rate: 0.0026
Epoch 28/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 650us/step - loss: 27.5039 - mae: 3.8897 - learning_rate: 0.0026
Epoch 29/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 663us/step - loss: 27.9154 - mae: 3.9385 - learning_rate: 0.0026
Epoch 30/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 725us/step - loss: 26.9807 - mae: 3.8716 - learning_rate: 0.0026
Epoch 31/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 630us/step - loss: 27.2608 - mae: 3.8728 - learning_rate: 0.0026
Epoch 32/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 646us/step - loss: 27.9458 - mae: 3.9391 - learning_rate: 0.0026
Epoch 33/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - loss: 27.6223 - mae: 3.9119 - learning_rate: 0.0026
Epoch 34/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 630us/step - loss: 27.1109 - mae: 3.8997 - learning_rate: 0.0026
Epoch 35/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 845us/step - loss: 27.1080 - mae: 3.8870 - learning_rate: 0.0026
Epoch 36/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 802us/step - loss: 27.0858 - mae: 3.8753 - learning_rate: 0.0026
Epoch 37/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 866us/step - loss: 27.0713 - mae: 3.8679 - learning_rate: 0.0026
Epoch 38/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - loss: 26.9064 - mae: 3.8562 - learning_rate: 0.0026
Epoch 39/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 720us/step - loss: 26.5533 - mae: 3.8314 - learning_rate: 0.0026
Epoch 40/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 649us/step - loss: 27.1300 - mae: 3.8612 - learning_rate: 0.0026
Epoch 41/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 750us/step - loss: 26.2254 - mae: 3.8190 - learning_rate: 0.0026
Epoch 42/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - loss: 26.5151 - mae: 3.8390 - learning_rate: 0.0026
Epoch 43/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 713us/step - loss: 27.5290 - mae: 3.8964 - learning_rate: 0.0026
Epoch 44/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 660us/step - loss: 26.3908 - mae: 3.8485 - learning_rate: 0.0026
Epoch 45/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 723us/step - loss: 26.9338 - mae: 3.8581 - learning_rate: 0.0026
Epoch 46/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 692us/step - loss: 26.2389 - mae: 3.7954 - learning_rate: 0.0026
Epoch 47/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 736us/step - loss: 26.8822 - mae: 3.8503 - learning_rate: 0.0026
Epoch 48/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - loss: 27.4303 - mae: 3.8964 - learning_rate: 0.0026
Epoch 49/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 807us/step - loss: 27.0647 - mae: 3.8710 - learning_rate: 0.0026
Epoch 50/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 26.8866 - mae: 3.8592 - learning_rate: 0.0026
Epoch 51/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 692us/step - loss: 26.6532 - mae: 3.8435 - learning_rate: 0.0026
Epoch 52/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 727us/step - loss: 25.9031 - mae: 3.7594 - learning_rate: 0.0013
Epoch 53/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 670us/step - loss: 25.3007 - mae: 3.7184 - learning_rate: 0.0013
Epoch 54/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 25.4156 - mae: 3.7321 - learning_rate: 0.0013
Epoch 55/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 853us/step - loss: 25.1527 - mae: 3.7135 - learning_rate: 0.0013
Epoch 56/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 917us/step - loss: 24.4605 - mae: 3.6706 - learning_rate: 0.0013
Epoch 57/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 25.0162 - mae: 3.6966 - learning_rate: 0.0013
Epoch 58/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 860us/step - loss: 25.2820 - mae: 3.7235 - learning_rate: 0.0013
Epoch 59/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 800us/step - loss: 24.8086 - mae: 3.6996 - learning_rate: 0.0013
Epoch 60/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 941us/step - loss: 25.3789 - mae: 3.7276 - learning_rate: 0.0013
Epoch 61/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 836us/step - loss: 24.9191 - mae: 3.7025 - learning_rate: 0.0013
Epoch 62/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 674us/step - loss: 24.8874 - mae: 3.6992 - learning_rate: 6.4134e-04
Epoch 63/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 767us/step - loss: 24.1450 - mae: 3.6406 - learning_rate: 6.4134e-04
Epoch 64/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - loss: 24.2414 - mae: 3.6477 - learning_rate: 6.4134e-04
Epoch 65/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 674us/step - loss: 24.4939 - mae: 3.6647 - learning_rate: 6.4134e-04
Epoch 66/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - loss: 24.2724 - mae: 3.6587 - learning_rate: 6.4134e-04
Epoch 67/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 739us/step - loss: 24.1882 - mae: 3.6436 - learning_rate: 6.4134e-04
Epoch 68/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 674us/step - loss: 24.4261 - mae: 3.6482 - learning_rate: 6.4134e-04
Epoch 69/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - loss: 23.4712 - mae: 3.5950 - learning_rate: 6.4134e-04
Epoch 70/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - loss: 24.5003 - mae: 3.6784 - learning_rate: 3.2067e-04
Epoch 71/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 24.9160 - mae: 3.6480 - learning_rate: 3.2067e-04
Epoch 72/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 23.2583 - mae: 3.5807 - learning_rate: 3.2067e-04
Epoch 73/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 963us/step - loss: 23.9855 - mae: 3.6219 - learning_rate: 3.2067e-04
Epoch 74/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - loss: 23.9763 - mae: 3.6132 - learning_rate: 3.2067e-04
Epoch 75/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - loss: 23.9697 - mae: 3.6214 - learning_rate: 3.2067e-04
Epoch 76/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 740us/step - loss: 24.2050 - mae: 3.6359 - learning_rate: 3.2067e-04
Epoch 77/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - loss: 23.6347 - mae: 3.6052 - learning_rate: 3.2067e-04
Epoch 78/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - loss: 23.4654 - mae: 3.5787 - learning_rate: 3.2067e-04
Epoch 79/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 711us/step - loss: 23.4528 - mae: 3.5939 - learning_rate: 3.2067e-04
Epoch 80/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 23.9962 - mae: 3.6282 - learning_rate: 3.2067e-04
Epoch 81/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 24.1096 - mae: 3.6342 - learning_rate: 1.6033e-04
Epoch 82/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 24.0554 - mae: 3.6251 - learning_rate: 1.6033e-04
Epoch 83/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 887us/step - loss: 23.6481 - mae: 3.5932 - learning_rate: 1.6033e-04
Epoch 84/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 820us/step - loss: 23.7184 - mae: 3.6111 - learning_rate: 1.6033e-04
Epoch 85/100
1643/1643 ━━━━━━━━━━━━━━━━━━━━ 1s 756us/step - loss: 23.5984 - mae: 3.5727 - learning_rate: 1.6033e-04
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

### 履歴
___
LIGHTGBM：ベイズ最適化の結果
Best params: {'num_leaves': 21, 'learning_rate': 0.0926973092334304, 'feature_fraction': 0.9533804854356259, 'bagging_fraction': 0.9723501183105292, 'bagging_freq': 10, 'min_child_samples': 43, 'objective': 'regression', 'metric': 'rmse', 'boosting_type': 'gbdt', 'verbose': -1, 'random_state': 42}  
Best CV RMSE: 2.51734282613965  
Selected features: 73/92
___

In [ ]:
predictions_sequential

array([36.01848 , 36.382614, 37.331905, ..., 65.88715 , 63.860985,
       62.69906 ], dtype=float32)

In [16]:
print("finish")

finish