# 逐次予測

前処理済みのデータを用いてモデルを構築し、評価する

- 目的変数: `price_actual`
- モデル: LightGBM, RandomForest, SVR, NeuralNetwork のいずれか
- 評価指標: RMSE
- ハイパーパラメータチューニング: ベイズ最適化

## 1. ライブラリのインポートとデータ読み込み

In [1]:
# 自動ローディング
%load_ext autoreload
%autoreload 2

In [2]:
# アクティベート
!source ../../.venv/bin/activate

In [3]:
# LightGBM特有のエラー対策
#!brew install libomp
#!pip uninstall lightgbm
#!pip install lightgbm

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

# データ読み込み用の関数をインポート
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
from src.data_loader import check_missing_values
from src.modeling import train_and_predict

# データディレクトリ
PROJECT_ROOT = Path.cwd().parent
DATA_DIR = PROJECT_ROOT / 'data'
SUBMISSION = DATA_DIR / 'submission'

os.makedirs(SUBMISSION, exist_ok=True)

print(DATA_DIR)
# 前処理済みデータの読み込み
train = pd.read_csv(DATA_DIR / 'train_processed.csv')
test = pd.read_csv(DATA_DIR / 'test_processed.csv')

print('train shape:', train.shape)
print('test shape:', test.shape)

/Users/m0122wt/Desktop/02.プライベート/01.ノウハウ/07.データ分析/notebook/signate_smbc_202506/data
train shape: (26280, 94)
test shape: (8760, 93)

## 2. 特徴量・目的変数の設定

In [5]:
# 目的変数
target_col = 'price_actual'

# 説明変数（目的変数とtime列以外）
drop_cols = ['time', target_col] if target_col in train.columns else ['time']
feature_cols = [col for col in train.columns if col not in drop_cols]

X = train[feature_cols]
y = train[target_col] if target_col in train.columns else train.iloc[:, -1]  # 念のため

print('Features:', feature_cols)
print('Target:', target_col)
print('X shape:', X.shape)
print('y shape:', y.shape)

Features: ['generation_biomass', 'generation_fossil_brown_coal/lignite', 'generation_fossil_gas', 'generation_fossil_hard_coal', 'generation_fossil_oil', 'generation_hydro_pumped_storage_consumption', 'generation_hydro_run_of_river_and_poundage', 'generation_hydro_water_reservoir', 'generation_nuclear', 'generation_other', 'generation_other_renewable', 'generation_solar', 'generation_waste', 'generation_wind_onshore', 'total_load_actual', 'valencia_pressure', 'valencia_humidity', 'valencia_wind_speed', 'valencia_wind_deg', 'valencia_rain_1h', 'valencia_rain_3h', 'valencia_snow_3h', 'valencia_clouds_all', 'madrid_pressure', 'madrid_humidity', 'madrid_wind_speed', 'madrid_wind_deg', 'madrid_rain_1h', 'madrid_rain_3h', 'madrid_snow_3h', 'madrid_clouds_all', 'bilbao_pressure', 'bilbao_humidity', 'bilbao_wind_speed', 'bilbao_wind_deg', 'bilbao_rain_1h', 'bilbao_rain_3h', 'bilbao_snow_3h', 'bilbao_clouds_all', 'barcelona_pressure', 'barcelona_humidity', 'barcelona_wind_speed', 'barcelona_wind_deg', 'barcelona_rain_1h', 'barcelona_rain_3h', 'barcelona_snow_3h', 'barcelona_clouds_all', 'seville_pressure', 'seville_humidity', 'seville_wind_speed', 'seville_wind_deg', 'seville_rain_1h', 'seville_rain_3h', 'seville_snow_3h', 'seville_clouds_all', 'hour', 'day_of_week', 'month', 'day', 'year', 'is_weekend', 'is_holiday', 'is_peak_hour', 'is_off_hour', 'generation_biomass_ratio', 'generation_fossil_brown_coal/lignite_ratio', 'generation_fossil_gas_ratio', 'generation_fossil_hard_coal_ratio', 'generation_fossil_oil_ratio', 'generation_hydro_pumped_storage_consumption_ratio', 'generation_hydro_run_of_river_and_poundage_ratio', 'generation_hydro_water_reservoir_ratio', 'generation_nuclear_ratio', 'generation_other_ratio', 'generation_other_renewable_ratio', 'generation_solar_ratio', 'generation_waste_ratio', 'generation_wind_onshore_ratio', 'non_fossil_generation', 'demand_non_fossil_diff', 'avg_temp', 'var_temp', 'avg_diff_temp', 'var_diff_temp', 'avg_weighted_weather_main', 'var_weighted_weather_main', 'price_actual_lag1', 'price_actual_lag24', 'is_holiday_or_weekend_flag', 'is_next_day_holiday_or_weekend_flag', 'is_previous_day_holiday_or_weekend_flag', 'consecutive_holiday_or_weekend_flag']
Target: price_actual
X shape: (26280, 92)
y shape: (26280,)

In [6]:
# 学習とテストデータでカラムの構成に違いがないか確認
diff_features = set(train.columns) - set(test.columns)
print("差分があるカラム:")
print(sorted(list(diff_features)))

# 欠損値の確認
check_missing_values(train)
check_missing_values(test)

差分があるカラム:
['price_actual']
欠損値があるカラム、欠損値の数、全レコードに対する割合:

Empty DataFrame
Columns: [missing_count, missing_ratio]
Index: []

欠損値があるカラム、欠損値の数、全レコードに対する割合:

Empty DataFrame
Columns: [missing_count, missing_ratio]
Index: []

## 3. 学習・検証

In [ ]:
%%time
filename = 'submission_nn'

# 通常の予測
model, predictions = train_and_predict(
    model_type='neural_network',
    train_df=train,
    test_df=test,
    target_col='price_actual',
    optimize=True,
    sequential=False,  # 通常予測
    output_path=SUBMISSION,
    filename=filename
)

### 履歴
___
LIGHTGBM：ベイズ最適化の結果
Best params: {'num_leaves': 20, 'learning_rate': 0.07056499143559153, 'feature_fraction': 0.930666633751073, 'bagging_fraction': 0.8764523692423547, 'bagging_freq': 9, 'min_child_samples': 35, 'objective': 'regression', 'metric': 'rmse', 'boosting_type': 'gbdt', 'verbose': -1, 'random_state': 42}  
Best CV RMSE: 2.517122779389563  
Selected features: 73/92  
___
NEURAL_NETWORK：ベイズ最適化の結果
Best params: {'layer1_units': 48, 'layer2_units': 121, 'layer3_units': 8, 'dropout_rate': 0.16207371516723865, 'learning_rate': 0.005173979484789956, 'batch_size': 16}  
Best CV RMSE: 3.7179227519163134  
___

In [ ]:
predictions

In [ ]:
%%time

filename_sequential = 'submission_nn_sequential'

# 逐次予測（ラグ特徴量を考慮）
model_sequential, predictions_sequential = train_and_predict(
    model_type='neural_network',
    train_df=train,
    test_df=test,
    target_col='price_actual',
    optimize=True,
    sequential=True,  # 逐次予測
    output_path=SUBMISSION,
    filename=filename_sequential
)

[I 2025-06-29 16:16:17,234] A new study created in memory with name: no-name-50bb1049-8f21-4195-a625-62b95eff998c

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step

[I 2025-06-29 16:18:38,151] Trial 0 finished with value: 5.074263028514065 and parameters: {'layer1_units': 231, 'layer2_units': 119, 'layer3_units': 41, 'dropout_rate': 0.45816053802580203, 'learning_rate': 0.0017795345905176271, 'batch_size': 16}. Best is trial 0 with value: 5.074263028514065.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 610us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step

[I 2025-06-29 16:21:10,988] Trial 1 finished with value: 4.793218494337585 and parameters: {'layer1_units': 72, 'layer2_units': 85, 'layer3_units': 8, 'dropout_rate': 0.3424013268551534, 'learning_rate': 0.007644347243250683, 'batch_size': 16}. Best is trial 1 with value: 4.793218494337585.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step

[I 2025-06-29 16:22:53,182] Trial 2 finished with value: 6.181810953841236 and parameters: {'layer1_units': 42, 'layer2_units': 18, 'layer3_units': 39, 'dropout_rate': 0.44576777895251607, 'learning_rate': 0.003557387568070253, 'batch_size': 16}. Best is trial 1 with value: 4.793218494337585.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 656us/step

[I 2025-06-29 16:24:29,077] Trial 3 finished with value: 4.200605622605982 and parameters: {'layer1_units': 101, 'layer2_units': 18, 'layer3_units': 28, 'dropout_rate': 0.24443577352425724, 'learning_rate': 0.009254430469100386, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step

[I 2025-06-29 16:25:38,968] Trial 4 finished with value: 5.713271409081391 and parameters: {'layer1_units': 188, 'layer2_units': 106, 'layer3_units': 14, 'dropout_rate': 0.3284372308853414, 'learning_rate': 0.0005825499654002242, 'batch_size': 32}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step

[I 2025-06-29 16:27:14,756] Trial 5 finished with value: 4.510507254787202 and parameters: {'layer1_units': 84, 'layer2_units': 34, 'layer3_units': 58, 'dropout_rate': 0.2151765746589791, 'learning_rate': 0.009645845894078074, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step

[I 2025-06-29 16:28:38,271] Trial 6 finished with value: 5.316474290228831 and parameters: {'layer1_units': 217, 'layer2_units': 62, 'layer3_units': 21, 'dropout_rate': 0.1038225547174335, 'learning_rate': 0.0006752547941877406, 'batch_size': 32}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step

[I 2025-06-29 16:30:46,118] Trial 7 finished with value: 5.044489814408023 and parameters: {'layer1_units': 247, 'layer2_units': 67, 'layer3_units': 49, 'dropout_rate': 0.2928040201066733, 'learning_rate': 0.0016928893760835395, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 643us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step

[I 2025-06-29 16:32:38,015] Trial 8 finished with value: 5.696168508024507 and parameters: {'layer1_units': 214, 'layer2_units': 63, 'layer3_units': 8, 'dropout_rate': 0.3342820115766887, 'learning_rate': 0.002312966558592089, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 626us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 616us/step

[I 2025-06-29 16:33:27,810] Trial 9 finished with value: 6.379744267447819 and parameters: {'layer1_units': 67, 'layer2_units': 79, 'layer3_units': 8, 'dropout_rate': 0.14243901217802324, 'learning_rate': 0.0005921992607495194, 'batch_size': 64}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step

[I 2025-06-29 16:34:26,315] Trial 10 finished with value: 6.640201905444121 and parameters: {'layer1_units': 134, 'layer2_units': 43, 'layer3_units': 28, 'dropout_rate': 0.21511722331783228, 'learning_rate': 0.0001380342605887115, 'batch_size': 64}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step

[I 2025-06-29 16:36:07,342] Trial 11 finished with value: 4.404029043592274 and parameters: {'layer1_units': 123, 'layer2_units': 18, 'layer3_units': 63, 'dropout_rate': 0.22135081453025682, 'learning_rate': 0.009841297712717545, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step

[I 2025-06-29 16:37:47,589] Trial 12 finished with value: 4.709769056426931 and parameters: {'layer1_units': 127, 'layer2_units': 16, 'layer3_units': 62, 'dropout_rate': 0.23178976654729386, 'learning_rate': 0.005216397810282644, 'batch_size': 16}. Best is trial 3 with value: 4.200605622605982.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step

[I 2025-06-29 16:40:24,854] Trial 13 finished with value: 3.8802684336887294 and parameters: {'layer1_units': 160, 'layer2_units': 38, 'layer3_units': 27, 'dropout_rate': 0.26200507726198113, 'learning_rate': 0.0048079838507547245, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step

[I 2025-06-29 16:41:02,968] Trial 14 finished with value: 5.437306404252508 and parameters: {'layer1_units': 171, 'layer2_units': 40, 'layer3_units': 29, 'dropout_rate': 0.3946165704009317, 'learning_rate': 0.00374890968649295, 'batch_size': 64}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step

[I 2025-06-29 16:42:24,088] Trial 15 finished with value: 5.681424358700821 and parameters: {'layer1_units': 102, 'layer2_units': 48, 'layer3_units': 28, 'dropout_rate': 0.28092905037690025, 'learning_rate': 0.0002098117602848322, 'batch_size': 32}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 16:44:21,883] Trial 16 finished with value: 3.9842364681282434 and parameters: {'layer1_units': 163, 'layer2_units': 29, 'layer3_units': 20, 'dropout_rate': 0.16839202032287665, 'learning_rate': 0.005032049839442836, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step

[I 2025-06-29 16:46:24,817] Trial 17 finished with value: 4.671457806194619 and parameters: {'layer1_units': 170, 'layer2_units': 31, 'layer3_units': 19, 'dropout_rate': 0.15223687943054448, 'learning_rate': 0.0010848851901907016, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 538us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step

[I 2025-06-29 16:48:05,503] Trial 18 finished with value: 4.987303459980753 and parameters: {'layer1_units': 159, 'layer2_units': 51, 'layer3_units': 21, 'dropout_rate': 0.16526270057109949, 'learning_rate': 0.004641146913641022, 'batch_size': 32}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step

[I 2025-06-29 16:49:03,864] Trial 19 finished with value: 4.798873074783791 and parameters: {'layer1_units': 198, 'layer2_units': 97, 'layer3_units': 33, 'dropout_rate': 0.16933152769087334, 'learning_rate': 0.0024831091412395217, 'batch_size': 64}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step

[I 2025-06-29 16:50:46,944] Trial 20 finished with value: 4.803532446333111 and parameters: {'layer1_units': 154, 'layer2_units': 29, 'layer3_units': 46, 'dropout_rate': 0.10556135701752106, 'learning_rate': 0.0002826800896007474, 'batch_size': 16}. Best is trial 13 with value: 3.8802684336887294.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step

[I 2025-06-29 16:52:31,332] Trial 21 finished with value: 3.876923587097753 and parameters: {'layer1_units': 104, 'layer2_units': 27, 'layer3_units': 24, 'dropout_rate': 0.2521833960188156, 'learning_rate': 0.006747799457784578, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 16:54:19,683] Trial 22 finished with value: 4.098280266226412 and parameters: {'layer1_units': 141, 'layer2_units': 52, 'layer3_units': 16, 'dropout_rate': 0.2643419750033902, 'learning_rate': 0.006036223373022402, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 613us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step

[I 2025-06-29 16:55:45,860] Trial 23 finished with value: 4.583354773497168 and parameters: {'layer1_units': 107, 'layer2_units': 29, 'layer3_units': 24, 'dropout_rate': 0.17970070470048177, 'learning_rate': 0.0031012207899636214, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step

[I 2025-06-29 16:57:31,833] Trial 24 finished with value: 4.057573024445409 and parameters: {'layer1_units': 186, 'layer2_units': 37, 'layer3_units': 34, 'dropout_rate': 0.36769744404441457, 'learning_rate': 0.00677390702794368, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step

[I 2025-06-29 16:59:20,890] Trial 25 finished with value: 3.903484769553708 and parameters: {'layer1_units': 148, 'layer2_units': 27, 'layer3_units': 16, 'dropout_rate': 0.2618145878335157, 'learning_rate': 0.004914964000322214, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

[I 2025-06-29 17:01:03,357] Trial 26 finished with value: 5.555649008698103 and parameters: {'layer1_units': 38, 'layer2_units': 55, 'layer3_units': 14, 'dropout_rate': 0.3118908687527547, 'learning_rate': 0.0013604553489171085, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step

[I 2025-06-29 17:02:45,237] Trial 27 finished with value: 4.614513411350089 and parameters: {'layer1_units': 117, 'layer2_units': 25, 'layer3_units': 25, 'dropout_rate': 0.26262291868517645, 'learning_rate': 0.0027491794202358522, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 528us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step

[I 2025-06-29 17:03:25,022] Trial 28 finished with value: 5.521591752906142 and parameters: {'layer1_units': 144, 'layer2_units': 40, 'layer3_units': 16, 'dropout_rate': 0.4104880965800561, 'learning_rate': 0.006872342470003896, 'batch_size': 64}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step

[I 2025-06-29 17:04:52,936] Trial 29 finished with value: 5.130221208960801 and parameters: {'layer1_units': 90, 'layer2_units': 75, 'layer3_units': 37, 'dropout_rate': 0.19700434082368723, 'learning_rate': 0.001959391708264458, 'batch_size': 32}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 629us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

[I 2025-06-29 17:07:17,525] Trial 30 finished with value: 4.942246008915619 and parameters: {'layer1_units': 60, 'layer2_units': 46, 'layer3_units': 33, 'dropout_rate': 0.2611281437285348, 'learning_rate': 0.003952905051667406, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step

[I 2025-06-29 17:09:38,594] Trial 31 finished with value: 4.388172100269233 and parameters: {'layer1_units': 160, 'layer2_units': 128, 'layer3_units': 24, 'dropout_rate': 0.29863958929469125, 'learning_rate': 0.0053434046885266805, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step

[I 2025-06-29 17:11:48,721] Trial 32 finished with value: 3.966196444394572 and parameters: {'layer1_units': 172, 'layer2_units': 24, 'layer3_units': 19, 'dropout_rate': 0.19198681737751772, 'learning_rate': 0.004745872964637229, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step

[I 2025-06-29 17:13:24,956] Trial 33 finished with value: 4.848623228139817 and parameters: {'layer1_units': 187, 'layer2_units': 24, 'layer3_units': 13, 'dropout_rate': 0.48715771258717167, 'learning_rate': 0.007347413278312054, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step

[I 2025-06-29 17:15:40,634] Trial 34 finished with value: 4.2220808814206645 and parameters: {'layer1_units': 141, 'layer2_units': 24, 'layer3_units': 11, 'dropout_rate': 0.20025985254694414, 'learning_rate': 0.0038729417171148865, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 617us/step

[I 2025-06-29 17:17:44,940] Trial 35 finished with value: 4.512844546416352 and parameters: {'layer1_units': 178, 'layer2_units': 34, 'layer3_units': 19, 'dropout_rate': 0.25763390868707475, 'learning_rate': 0.003172223050558643, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 657us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step

[I 2025-06-29 17:19:19,493] Trial 36 finished with value: 4.362338230267158 and parameters: {'layer1_units': 202, 'layer2_units': 22, 'layer3_units': 41, 'dropout_rate': 0.3495540925529042, 'learning_rate': 0.007813265382854321, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 618us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step

[I 2025-06-29 17:21:06,339] Trial 37 finished with value: 4.819765828262423 and parameters: {'layer1_units': 87, 'layer2_units': 58, 'layer3_units': 30, 'dropout_rate': 0.23416161933560936, 'learning_rate': 0.0017032590013533627, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 645us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step

[I 2025-06-29 17:23:06,335] Trial 38 finished with value: 5.498987794441444 and parameters: {'layer1_units': 114, 'layer2_units': 94, 'layer3_units': 25, 'dropout_rate': 0.31413125354794474, 'learning_rate': 0.0008784677191219725, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 525us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step

[I 2025-06-29 17:24:14,044] Trial 39 finished with value: 5.424504141513313 and parameters: {'layer1_units': 231, 'layer2_units': 35, 'layer3_units': 16, 'dropout_rate': 0.24518404482570433, 'learning_rate': 0.0004263210687753897, 'batch_size': 32}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step

[I 2025-06-29 17:25:36,563] Trial 40 finished with value: 4.526995081993984 and parameters: {'layer1_units': 131, 'layer2_units': 18, 'layer3_units': 23, 'dropout_rate': 0.27470656962423273, 'learning_rate': 0.008149996837600442, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 638us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step

[I 2025-06-29 17:27:12,893] Trial 41 finished with value: 4.298458958047966 and parameters: {'layer1_units': 163, 'layer2_units': 27, 'layer3_units': 19, 'dropout_rate': 0.13368977959399322, 'learning_rate': 0.004934358063487169, 'batch_size': 16}. Best is trial 21 with value: 3.876923587097753.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step

[I 2025-06-29 17:29:03,749] Trial 42 finished with value: 3.803042084025541 and parameters: {'layer1_units': 152, 'layer2_units': 32, 'layer3_units': 21, 'dropout_rate': 0.2084003783040671, 'learning_rate': 0.004209882321912923, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step

[I 2025-06-29 17:30:57,451] Trial 43 finished with value: 4.32770487822272 and parameters: {'layer1_units': 177, 'layer2_units': 44, 'layer3_units': 11, 'dropout_rate': 0.19890986854622472, 'learning_rate': 0.004048376954738159, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step

[I 2025-06-29 17:32:25,382] Trial 44 finished with value: 4.535062081732334 and parameters: {'layer1_units': 154, 'layer2_units': 37, 'layer3_units': 27, 'dropout_rate': 0.23951964483520002, 'learning_rate': 0.0022609258738724492, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step

[I 2025-06-29 17:34:05,452] Trial 45 finished with value: 4.36564886470922 and parameters: {'layer1_units': 145, 'layer2_units': 21, 'layer3_units': 17, 'dropout_rate': 0.21249795584279516, 'learning_rate': 0.0059039903646179795, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 523us/step

[I 2025-06-29 17:34:48,825] Trial 46 finished with value: 4.973814029113038 and parameters: {'layer1_units': 151, 'layer2_units': 32, 'layer3_units': 31, 'dropout_rate': 0.1862350509185439, 'learning_rate': 0.008582523127940705, 'batch_size': 64}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step

[I 2025-06-29 17:36:55,612] Trial 47 finished with value: 4.561239355043058 and parameters: {'layer1_units': 199, 'layer2_units': 69, 'layer3_units': 22, 'dropout_rate': 0.2817386115484715, 'learning_rate': 0.003385431189179845, 'batch_size': 16}. Best is trial 42 with value: 3.803042084025541.

137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step
137/137 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step

### 履歴
___
LIGHTGBM：ベイズ最適化の結果
Best params: {'num_leaves': 21, 'learning_rate': 0.0926973092334304, 'feature_fraction': 0.9533804854356259, 'bagging_fraction': 0.9723501183105292, 'bagging_freq': 10, 'min_child_samples': 43, 'objective': 'regression', 'metric': 'rmse', 'boosting_type': 'gbdt', 'verbose': -1, 'random_state': 42}  
Best CV RMSE: 2.51734282613965  
Selected features: 73/92
___

In [ ]:
predictions_sequential